/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ManageMasterFlightSchedule;

import Business.Customer;
import Business.CustomerDirectory;
import Business.Flight;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.Objects;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Dinesh Kumar
 */
public class FlightSearchResultJPanel extends javax.swing.JPanel {

    /**
     * Creates new form FlightFoundDetailJPanel
     */
    private final JPanel cardLayoutJPanel;
    private final Flight selectedFlight;

    FlightSearchResultJPanel(JPanel cardLayoutJPanel, Flight selectedFlight) {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        initComponents();
        this.cardLayoutJPanel = cardLayoutJPanel;
        this.selectedFlight = selectedFlight;
        flightNumbTxt.setText(selectedFlight.getFlightNumber());
        if(selectedFlight.getFlightPrice() == null){
            priceTxt.setText("100");
        }else{
            priceTxt.setText(Double.toString(selectedFlight.getFlightPrice()));
        }
        seatSelectComboBoxBuild();
    }
    /* Provide seat combo box */
    public void seatSelectComboBoxBuild() {
        DefaultComboBoxModel cBmodel = new DefaultComboBoxModel();
        cBmodel.addElement("Select Seat");
        for (int i = 0; i < selectedFlight.getFlightSeats().getSeat().size(); i++) {
            cBmodel.addElement(selectedFlight.getFlightSeats().getSeat().get(i));
        }
        seatCB.setModel(cBmodel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        firstNameTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        lastNameTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        ageTxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        phoneTxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        priceTxt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        flightNumbTxt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        seatCB = new javax.swing.JComboBox<>();
        btnBook = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 204, 255));

        btnBack.setBackground(new java.awt.Color(255, 204, 102));
        btnBack.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnBack.setText("Cancel");
        btnBack.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 0, 0), new java.awt.Color(204, 204, 204), null));
        btnBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel1.setText("FirstName");

        firstNameTxt.setBackground(new java.awt.Color(255, 204, 102));

        jLabel2.setText("LastName");

        lastNameTxt.setBackground(new java.awt.Color(255, 204, 102));

        jLabel3.setText("Age");

        ageTxt.setBackground(new java.awt.Color(255, 204, 102));

        jLabel4.setText("Phone");

        phoneTxt.setBackground(new java.awt.Color(255, 204, 102));

        jLabel6.setText("Price");

        priceTxt.setBackground(new java.awt.Color(255, 204, 102));
        priceTxt.setEnabled(false);

        jLabel7.setText("FlightNumber");

        flightNumbTxt.setBackground(new java.awt.Color(255, 204, 102));
        flightNumbTxt.setEnabled(false);

        jLabel8.setText("Seat Choice");

        seatCB.setBackground(new java.awt.Color(255, 204, 102));
        seatCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Seat" }));
        seatCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatCBActionPerformed(evt);
            }
        });

        btnBook.setBackground(new java.awt.Color(255, 204, 102));
        btnBook.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnBook.setText("Confirm Booking");
        btnBook.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 0, 0), new java.awt.Color(204, 204, 204), null));
        btnBook.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setText("Booking Page");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(231, 231, 231)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(priceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(phoneTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel1))
                            .addComponent(jLabel3))
                        .addGap(120, 120, 120)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ageTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(firstNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lastNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(flightNumbTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                            .addComponent(seatCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(btnBook, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(263, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(firstNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lastNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(ageTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(phoneTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(priceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(flightNumbTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(seatCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBook, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(192, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    /* On click of book check if every info is added about customer */
    private void btnBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookActionPerformed

        if (firstNameTxt.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Please Enter First Name");
            return;
        }

        if (lastNameTxt.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Please Enter Last Name");
            return;
        }

        if (ageTxt.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Please Enter Your Age");
            return;
        }
        try {
            Integer.parseInt(ageTxt.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Please Enter Number for Age");
            return;
        }
        if (phoneTxt.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Please Enter Your Phone Number");
            return;
        }

        if (seatCB.getSelectedItem().equals("Select Seat")) {
            JOptionPane.showMessageDialog(null, "Please Select Seat No: ");
            return;
        }
        Customer newCustomer = new Customer();
        newCustomer.setCstFirstName(firstNameTxt.getText());
        newCustomer.setCstLastName(lastNameTxt.getText());
        newCustomer.setCstAge((int) Double.parseDouble(ageTxt.getText()));
        newCustomer.setCstPhoneNum(phoneTxt.getText());
        newCustomer.setCstFlight(selectedFlight);
        newCustomer.setCstSeat(seatCB.getSelectedItem().toString());

        CustomerDirectory.customerList.add(newCustomer);

        selectedFlight.getFlightSeats().getSeat().remove(seatCB.getSelectedItem());

        JOptionPane.showMessageDialog(null, "Flight Ticket Booked");
        cardLayoutJPanel.remove(this);
        CardLayout layout = (CardLayout) cardLayoutJPanel.getLayout();
        Component[] components = cardLayoutJPanel.getComponents();
        for (Component c : components) {
            if (c instanceof FlightFilterJPanel) {
                FlightFilterJPanel found = (FlightFilterJPanel) c;
                found.populateTable();
            }
        }
        layout.previous(cardLayoutJPanel);
    }//GEN-LAST:event_btnBookActionPerformed
    /* Onclick of back button go to prev jpanel */
    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        cardLayoutJPanel.remove(this);
        CardLayout layout = (CardLayout) cardLayoutJPanel.getLayout();
        Component[] c = cardLayoutJPanel.getComponents();
        for (Component cc : c) {
            if (cc instanceof FlightFilterJPanel) {
                FlightFilterJPanel found = (FlightFilterJPanel) cc;
                found.populateTable();
            }
        }
        layout.previous(cardLayoutJPanel);
    }//GEN-LAST:event_btnBackActionPerformed

    private void seatCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seatCBActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ageTxt;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnBook;
    private javax.swing.JTextField firstNameTxt;
    private javax.swing.JTextField flightNumbTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField lastNameTxt;
    private javax.swing.JTextField phoneTxt;
    private javax.swing.JTextField priceTxt;
    private javax.swing.JComboBox<String> seatCB;
    // End of variables declaration//GEN-END:variables
}
