/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;
/* Import CarCatalog and card layout packages */
import Business.CarCatalog;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author manushpatel
 */
public class AdminJPanel extends javax.swing.JPanel {
    
    /* Initalize variable to access throgh class */
    private JPanel menuContainer;
    private CarCatalog carCatalog;
    /**
     * Creates new form AdminJpanel
     */
    AdminJPanel(JPanel menuContainer, CarCatalog carCatalog) {
        initComponents();
        /* Initialize card container variables */
        this.menuContainer = menuContainer;
        this.carCatalog = carCatalog;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCreateCar = new javax.swing.JButton();
        btnViewCar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        btnCreateCar.setBackground(new java.awt.Color(102, 102, 102));
        btnCreateCar.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        btnCreateCar.setText("Create Car Details");
        btnCreateCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateCarActionPerformed(evt);
            }
        });

        btnViewCar.setBackground(new java.awt.Color(102, 102, 102));
        btnViewCar.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        btnViewCar.setText("View Car Details");
        btnViewCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewCarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(320, 320, 320)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnViewCar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCreateCar, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE))
                .addContainerGap(381, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(btnCreateCar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81)
                .addComponent(btnViewCar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(326, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateCarActionPerformed
        // TODO add your handling code here:
        /* On Create car details move card to next Jpanel having create view */
        CreateCarJPanel panel = new CreateCarJPanel(menuContainer,carCatalog);
        menuContainer.add("CreateCarJPanel",panel);
        CardLayout layout = (CardLayout) menuContainer.getLayout();
        layout.next(menuContainer);
    }//GEN-LAST:event_btnCreateCarActionPerformed

    private void btnViewCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewCarActionPerformed
        // TODO add your handling code here:
        /* On View car details move card to next Jpanel having view details section*/
        ViewCarJPanel panel = new ViewCarJPanel(menuContainer,carCatalog);
        menuContainer.add("ViewCarJPanel",panel);
        CardLayout layout = (CardLayout) menuContainer.getLayout();
        layout.next(menuContainer);
    }//GEN-LAST:event_btnViewCarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateCar;
    private javax.swing.JButton btnViewCar;
    // End of variables declaration//GEN-END:variables
}
