/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.Car;
import Business.CarCatalog;
import java.awt.CardLayout;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author manushpatel
 */
public class UserJFrame extends javax.swing.JFrame {
    /* Initialize Car Catalog object variable */
    private CarCatalog carCatalog;
    private CarCatalog resultCatalog;
    /**
     * Creates new form UserJPanel1
     */

    UserJFrame() throws IOException {
        initComponents();
        /* Initialize object of Car Catalog */
        this.carCatalog = new CarCatalog();
        this.resultCatalog = new CarCatalog();
        this.resultCatalog.setCarList(new ArrayList<Car>());
    }
    
    void showTable()
    {
        DefaultTableModel dtm = (DefaultTableModel) tblCars.getModel();
        dtm.setRowCount(0);
        for(Car car:resultCatalog.getCarList())
        {
            Object[] row = new Object[4];
            row[0] = car;
            row[1] = car.isIsAvailable();
            row[2] = car.getTimeAvailable();
            row[3] = car.isIsExpired();
            dtm.addRow(row);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SplitPane = new javax.swing.JSplitPane();
        topJPanel = new javax.swing.JPanel();
        listCarByManufacture = new javax.swing.JButton();
        listByManufactureYear = new javax.swing.JButton();
        btnFindCarBySeat = new javax.swing.JButton();
        listCarByCity = new javax.swing.JButton();
        btnListCarByModelNo = new javax.swing.JButton();
        btnListCarBySerialNo = new javax.swing.JButton();
        globalSearchBox = new javax.swing.JTextField();
        globalSearchBox1 = new javax.swing.JTextField();
        globalSearchBox2 = new javax.swing.JTextField();
        menuContainer = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCars = new javax.swing.JTable();
        btnFindUnavailableCar = new javax.swing.JButton();
        btnFindCar = new javax.swing.JButton();
        btnFindAvailableCar = new javax.swing.JButton();
        btnListExpiredCars = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        SplitPane.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        topJPanel.setPreferredSize(new java.awt.Dimension(1074, 500));

        listCarByManufacture.setText("List Car by Manufacturers");
        listCarByManufacture.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listCarByManufactureActionPerformed(evt);
            }
        });

        listByManufactureYear.setText("List Car Manufactured by Year");
        listByManufactureYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listByManufactureYearActionPerformed(evt);
            }
        });

        btnFindCarBySeat.setText("List Car by Seats");
        btnFindCarBySeat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindCarBySeatActionPerformed(evt);
            }
        });

        listCarByCity.setText("List Car by City");
        listCarByCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listCarByCityActionPerformed(evt);
            }
        });

        btnListCarByModelNo.setText("List Car by Model No");
        btnListCarByModelNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListCarByModelNoActionPerformed(evt);
            }
        });

        btnListCarBySerialNo.setText("List Car by Serial No");
        btnListCarBySerialNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListCarBySerialNoActionPerformed(evt);
            }
        });

        globalSearchBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                globalSearchBoxActionPerformed(evt);
            }
        });

        globalSearchBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                globalSearchBox1ActionPerformed(evt);
            }
        });

        globalSearchBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                globalSearchBox2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout topJPanelLayout = new javax.swing.GroupLayout(topJPanel);
        topJPanel.setLayout(topJPanelLayout);
        topJPanelLayout.setHorizontalGroup(
            topJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topJPanelLayout.createSequentialGroup()
                .addGroup(topJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(topJPanelLayout.createSequentialGroup()
                        .addGap(344, 344, 344)
                        .addComponent(listCarByManufacture, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(topJPanelLayout.createSequentialGroup()
                        .addGroup(topJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(topJPanelLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(listCarByCity)
                                .addGap(18, 18, 18)
                                .addComponent(btnListCarByModelNo, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, topJPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnListCarBySerialNo, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)))
                        .addComponent(listByManufactureYear, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(topJPanelLayout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(globalSearchBox, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(topJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(topJPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnFindCarBySeat, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(topJPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 361, Short.MAX_VALUE)
                        .addComponent(globalSearchBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66)
                        .addComponent(globalSearchBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(337, 337, 337))))
        );
        topJPanelLayout.setVerticalGroup(
            topJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topJPanelLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(topJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, topJPanelLayout.createSequentialGroup()
                        .addComponent(globalSearchBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addGroup(topJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(listCarByCity)
                            .addComponent(listByManufactureYear)
                            .addComponent(btnListCarByModelNo))
                        .addGap(18, 18, 18)
                        .addGroup(topJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(listCarByManufacture)
                            .addComponent(btnListCarBySerialNo))
                        .addGap(31, 31, 31))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, topJPanelLayout.createSequentialGroup()
                        .addGroup(topJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(globalSearchBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(globalSearchBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addComponent(btnFindCarBySeat)
                        .addGap(32, 32, 32))))
        );

        SplitPane.setLeftComponent(topJPanel);

        menuContainer.setLayout(new java.awt.CardLayout());
        SplitPane.setRightComponent(menuContainer);

        tblCars.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Car Name", "Is Available", "Available Time", "Is Expired"
            }
        ));
        jScrollPane1.setViewportView(tblCars);

        btnFindUnavailableCar.setText("Find Unavailable Cars");
        btnFindUnavailableCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindUnavailableCarActionPerformed(evt);
            }
        });

        btnFindCar.setText("Find First Available Car");
        btnFindCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindCarActionPerformed(evt);
            }
        });

        btnFindAvailableCar.setText("Find Available Cars");
        btnFindAvailableCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindAvailableCarActionPerformed(evt);
            }
        });

        btnListExpiredCars.setText("List Expired Certificate Cars");
        btnListExpiredCars.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListExpiredCarsActionPerformed(evt);
            }
        });

        jButton7.setText("Last Updated Fleet Catalog");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(SplitPane))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(190, 190, 190)
                                .addComponent(btnFindCar, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnFindAvailableCar, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnFindUnavailableCar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnListExpiredCars, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(444, 444, 444)
                                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 292, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1055, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SplitPane, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFindUnavailableCar)
                    .addComponent(btnFindCar)
                    .addComponent(btnFindAvailableCar)
                    .addComponent(btnListExpiredCars, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton7)
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnListExpiredCarsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListExpiredCarsActionPerformed
        // TODO add your handling code here:
        this.resultCatalog.setCarList(new ArrayList<Car>());
        for(Car car:carCatalog.getCarList())
        {
            if(car.isIsExpired())
            {
                this.resultCatalog.addCar(car);
            } 
        }
        showTable();
    }//GEN-LAST:event_btnListExpiredCarsActionPerformed
 
    private void btnFindCarBySeatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindCarBySeatActionPerformed
        // TODO add your handling code here:
        this.resultCatalog.setCarList(new ArrayList<Car>());
        int seatNumber = Integer.parseInt(globalSearchBox.getText());
        for(Car car:carCatalog.getCarList())
        {
            if(car.getSeatCapacity() == seatNumber)
            {
                this.resultCatalog.addCar(car);
            } 
        }
        showTable();
    }//GEN-LAST:event_btnFindCarBySeatActionPerformed

    private void globalSearchBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_globalSearchBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_globalSearchBoxActionPerformed

    private void btnListCarByModelNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListCarByModelNoActionPerformed
        // TODO add your handling code here:
        this.resultCatalog.setCarList(new ArrayList<Car>());
        String modelNo = globalSearchBox.getText();
        for(Car car:carCatalog.getCarList())
        {
            if(car.getModelNo() == modelNo)
            {
                this.resultCatalog.addCar(car);
            } 
        }
        showTable();
    }//GEN-LAST:event_btnListCarByModelNoActionPerformed

    private void listByManufactureYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listByManufactureYearActionPerformed
        // TODO add your handling code here:
        this.resultCatalog.setCarList(new ArrayList<Car>());
        int listByManufactureYear = Integer.parseInt(globalSearchBox.getText());
        for(Car car:carCatalog.getCarList())
        {
            if(car.getManufactureYear() == listByManufactureYear)
            {
                this.resultCatalog.addCar(car);
            } 
        }
        showTable();
    }//GEN-LAST:event_listByManufactureYearActionPerformed

    private void listCarByCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listCarByCityActionPerformed
        // TODO add your handling code here:
        this.resultCatalog.setCarList(new ArrayList<Car>());
        String cityName = globalSearchBox.getText();
        for(Car car:carCatalog.getCarList())
        {
            if(car.getModelNo() == cityName)
            {
                this.resultCatalog.addCar(car);
            } 
        }
        showTable();
    }//GEN-LAST:event_listCarByCityActionPerformed

    private void listCarByManufactureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listCarByManufactureActionPerformed
        // TODO add your handling code here:
        String manufactureName = globalSearchBox.getText();
        for(Car car:carCatalog.getCarList())
        {
            if(car.getManufacturerName() == manufactureName)
            {
                this.resultCatalog.addCar(car);
            } 
        }
        showTable();
    }//GEN-LAST:event_listCarByManufactureActionPerformed

    private void btnListCarBySerialNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListCarBySerialNoActionPerformed
        // TODO add your handling code here:
        this.resultCatalog.setCarList(new ArrayList<Car>());
        String serialNo = globalSearchBox.getText();
        for(Car car:carCatalog.getCarList())
        {
            if(car.getSerialNo() == serialNo)
            {
                this.resultCatalog.addCar(car);
            } 
        }
        showTable();
    }//GEN-LAST:event_btnListCarBySerialNoActionPerformed

    private void btnFindAvailableCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindAvailableCarActionPerformed
        // TODO add your handling code here:
        this.resultCatalog.setCarList(new ArrayList<Car>());
        for(Car car:carCatalog.getCarList())
        {
            if(car.isIsAvailable())
            {
                this.resultCatalog.addCar(car);
            } 
        }
        showTable();
    }//GEN-LAST:event_btnFindAvailableCarActionPerformed

    private void btnFindUnavailableCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindUnavailableCarActionPerformed
        // TODO add your handling code here:
        this.resultCatalog.setCarList(new ArrayList<Car>());
        for(Car car:carCatalog.getCarList())
        {
            if(!car.isIsAvailable())
            {
                this.resultCatalog.addCar(car);
            } 
        }
        showTable();
    }//GEN-LAST:event_btnFindUnavailableCarActionPerformed

    private void globalSearchBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_globalSearchBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_globalSearchBox1ActionPerformed

    private void globalSearchBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_globalSearchBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_globalSearchBox2ActionPerformed

    private void btnFindCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindCarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFindCarActionPerformed
     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new MainJframe().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(MainJframe.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSplitPane SplitPane;
    private javax.swing.JButton btnFindAvailableCar;
    private javax.swing.JButton btnFindCar;
    private javax.swing.JButton btnFindCarBySeat;
    private javax.swing.JButton btnFindUnavailableCar;
    private javax.swing.JButton btnListCarByModelNo;
    private javax.swing.JButton btnListCarBySerialNo;
    private javax.swing.JButton btnListExpiredCars;
    private javax.swing.JTextField globalSearchBox;
    private javax.swing.JTextField globalSearchBox1;
    private javax.swing.JTextField globalSearchBox2;
    private javax.swing.JButton jButton7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton listByManufactureYear;
    private javax.swing.JButton listCarByCity;
    private javax.swing.JButton listCarByManufacture;
    private javax.swing.JPanel menuContainer;
    private javax.swing.JTable tblCars;
    private javax.swing.JPanel topJPanel;
    // End of variables declaration//GEN-END:variables
}
