/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.Car;
import Business.CarCatalog;
import java.awt.CardLayout;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author manushpatel
 */
public class ViewCarDetailsJPanel extends javax.swing.JPanel {
    /* Initialize variables to use */
    private JPanel menuContainer;
    private Car car;
    private CarCatalog carCatalog;
    /**
     * Creates new form ViewCarDetailsJPanel
     */
    ViewCarDetailsJPanel(JPanel menuContainer, Car car) {
        initComponents();
        /* Populate the table with account details and disable save b utton */
        this.menuContainer = menuContainer;
        this.car = car;
        populateCarDetails();
        btnSaveCar.setEnabled(false);
        btnUpdate.setEnabled(true);
    }
    
    private void populateCarDetails() {   
        txtCarName.setText(car.getCarName());
        txtCityName.setText(car.getCity());
        txtDateTimeAvailable.setText(car.getTimeAvailable());
        checkBoxIsExpired.setSelected(car.isIsExpired());
        txtManufacturerName.setText(car.getCarName());
        txtManufactureYear.setText(Integer.toString(car.getManufactureYear()));
        txtSeatCapacity.setText(Integer.toString(car.getSeatCapacity()));
        txtSerialNo.setText(car.getSerialNo());
        txtModelNo.setText(car.getModelNo());
        chckBoxIsAvailable.setSelected(car.isIsAvailable());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblModelNo = new javax.swing.JLabel();
        txtManufacturerName = new javax.swing.JTextField();
        lblSeatCapacity = new javax.swing.JLabel();
        txtManufactureYear = new javax.swing.JTextField();
        lblIsExpired = new javax.swing.JLabel();
        lblCityName = new javax.swing.JLabel();
        chckBoxIsAvailable = new javax.swing.JCheckBox();
        txtSeatCapacity = new javax.swing.JTextField();
        checkBoxIsExpired = new javax.swing.JCheckBox();
        txtModelNo = new javax.swing.JTextField();
        btnSaveCar = new javax.swing.JButton();
        lblCreateCar = new javax.swing.JLabel();
        txtCityName = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        txtCarName = new javax.swing.JTextField();
        txtSerialNo = new javax.swing.JTextField();
        lblCarName = new javax.swing.JLabel();
        lblManufactureYear = new javax.swing.JLabel();
        lblDateTimeAvailable = new javax.swing.JLabel();
        lblIsAvailable = new javax.swing.JLabel();
        txtDateTimeAvailable = new javax.swing.JTextField();
        lblManufacturerName = new javax.swing.JLabel();
        lblSerialNo = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();

        lblModelNo.setText("Model No:");

        txtManufacturerName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtManufacturerNameActionPerformed(evt);
            }
        });

        lblSeatCapacity.setText("Seat Capacity:");

        txtManufactureYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtManufactureYearActionPerformed(evt);
            }
        });

        lblIsExpired.setText("Is Expired:");

        lblCityName.setText("City:");

        txtSeatCapacity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSeatCapacityActionPerformed(evt);
            }
        });

        txtModelNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtModelNoActionPerformed(evt);
            }
        });

        btnSaveCar.setText("Save");
        btnSaveCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveCarActionPerformed(evt);
            }
        });

        lblCreateCar.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblCreateCar.setText("Car Details");

        txtCityName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCityNameActionPerformed(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(204, 204, 204));
        btnBack.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        btnBack.setText("< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        txtCarName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCarNameActionPerformed(evt);
            }
        });

        txtSerialNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSerialNoActionPerformed(evt);
            }
        });

        lblCarName.setText("Name:");

        lblManufactureYear.setText("Manufacture Year:");

        lblDateTimeAvailable.setText("Time Available:");

        lblIsAvailable.setText("Is Available:");

        txtDateTimeAvailable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDateTimeAvailableActionPerformed(evt);
            }
        });

        lblManufacturerName.setText("Manufacturer Name:");

        lblSerialNo.setText("Serial No:");

        btnUpdate.setBackground(new java.awt.Color(204, 204, 204));
        btnUpdate.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCarName)
                    .addComponent(lblDateTimeAvailable)
                    .addComponent(lblSerialNo)
                    .addComponent(lblCityName)
                    .addComponent(lblManufactureYear))
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtSerialNo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(txtManufactureYear, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDateTimeAvailable, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCarName, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCityName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 207, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblIsAvailable)
                    .addComponent(lblManufacturerName)
                    .addComponent(lblSeatCapacity)
                    .addComponent(lblModelNo)
                    .addComponent(lblIsExpired))
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtManufacturerName, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                    .addComponent(txtSeatCapacity)
                    .addComponent(txtModelNo)
                    .addComponent(chckBoxIsAvailable)
                    .addComponent(checkBoxIsExpired))
                .addGap(117, 117, 117))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(81, 81, 81)
                        .addComponent(btnSaveCar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68)
                        .addComponent(btnUpdate)
                        .addGap(308, 308, 308))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblCreateCar, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(434, 434, 434))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblCreateCar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCarName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCarName))
                        .addGap(26, 26, 26))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(chckBoxIsAvailable)
                            .addComponent(lblIsAvailable))
                        .addGap(36, 36, 36)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDateTimeAvailable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDateTimeAvailable)
                    .addComponent(lblManufacturerName)
                    .addComponent(txtManufacturerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSeatCapacity)
                            .addComponent(txtSeatCapacity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtManufactureYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblManufactureYear))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblModelNo)
                            .addComponent(txtModelNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSerialNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSerialNo))))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIsExpired)
                    .addComponent(txtCityName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCityName)
                    .addComponent(checkBoxIsExpired))
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(btnSaveCar)
                    .addComponent(btnUpdate))
                .addContainerGap(187, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtManufacturerNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtManufacturerNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtManufacturerNameActionPerformed

    private void txtManufactureYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtManufactureYearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtManufactureYearActionPerformed

    private void txtSeatCapacityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSeatCapacityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSeatCapacityActionPerformed

    private void txtModelNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModelNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModelNoActionPerformed

    private void btnSaveCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveCarActionPerformed
        // TODO add your handling code here
        if(txtCarName.getText().equals("") || txtCityName.getText().equals("")
           || txtDateTimeAvailable.getText().equals("") || txtManufacturerName.getText().equals("")
           || txtManufactureYear.getText().equals("") || txtSeatCapacity.getText().equals("")
           || txtSerialNo.getText().equals("") || txtModelNo.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Please fill out all fields.");
        }else if(txtCityName.getText().matches("[0-9]+")){
            JOptionPane.showMessageDialog(null, "Please enter only alphabet "
            + "value for Bank Name!");
        }
        else if(!txtSeatCapacity.getText().matches("[0-9]+") || !txtManufactureYear.getText().matches("[0-9]+")){
            JOptionPane.showMessageDialog(null, "Please enter integer value for Seat and Manufacture Year !");
        }else{
            car.setCarName(txtCarName.getText());
            car.setCity(txtCityName.getText());
            car.setTimeAvailable(txtCityName.getText());
            car.setIsExpired(checkBoxIsExpired.isSelected());
            car.setManufacturerName(txtManufacturerName.getText());
            car.setManufactureYear(Integer.parseInt(txtManufactureYear.getText()));
            car.setSeatCapacity(Integer.parseInt(txtSeatCapacity.getText()));
            car.setSerialNo(txtSerialNo.getText());
            car.setModelNo(txtModelNo.getText());
            car.setCity(txtCityName.getText());
            car.setIsAvailable(chckBoxIsAvailable.isSelected());
            btnSaveCar.setEnabled(false);
            btnUpdate.setEnabled(true);
            /* Enable disable save and update buttons*/
            JOptionPane.showMessageDialog(null, "Car Details updated successfully.");
        }
       
    }//GEN-LAST:event_btnSaveCarActionPerformed

    private void txtCityNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCityNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCityNameActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        /* Travese to prev window on click of back button */
        menuContainer.remove(this);
        CardLayout layout = (CardLayout) menuContainer.getLayout();
        layout.previous(menuContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtCarNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCarNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCarNameActionPerformed

    private void txtSerialNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSerialNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSerialNoActionPerformed

    private void txtDateTimeAvailableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDateTimeAvailableActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDateTimeAvailableActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        /* On  update enable all the textfields and disable update button */
        txtCarName.setEnabled(true);
        txtCityName.setEnabled(true);
        txtDateTimeAvailable.setEnabled(true);
        checkBoxIsExpired.setEnabled(true);
        txtManufacturerName.setEnabled(true);
        txtManufactureYear.setEnabled(true);
        txtSeatCapacity.setEnabled(true);
        txtSerialNo.setEnabled(true);
        txtModelNo.setEnabled(true);
        chckBoxIsAvailable.setEnabled(true);
        btnSaveCar.setEnabled(true);
        btnUpdate.setEnabled(false);
    }//GEN-LAST:event_btnUpdateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSaveCar;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JCheckBox chckBoxIsAvailable;
    private javax.swing.JCheckBox checkBoxIsExpired;
    private javax.swing.JLabel lblCarName;
    private javax.swing.JLabel lblCityName;
    private javax.swing.JLabel lblCreateCar;
    private javax.swing.JLabel lblDateTimeAvailable;
    private javax.swing.JLabel lblIsAvailable;
    private javax.swing.JLabel lblIsExpired;
    private javax.swing.JLabel lblManufactureYear;
    private javax.swing.JLabel lblManufacturerName;
    private javax.swing.JLabel lblModelNo;
    private javax.swing.JLabel lblSeatCapacity;
    private javax.swing.JLabel lblSerialNo;
    private javax.swing.JTextField txtCarName;
    private javax.swing.JTextField txtCityName;
    private javax.swing.JTextField txtDateTimeAvailable;
    private javax.swing.JTextField txtManufactureYear;
    private javax.swing.JTextField txtManufacturerName;
    private javax.swing.JTextField txtModelNo;
    private javax.swing.JTextField txtSeatCapacity;
    private javax.swing.JTextField txtSerialNo;
    // End of variables declaration//GEN-END:variables
}
