/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SellerRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.Property.Property;
import Business.Property.PropertyDirectory;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.GovtEmpRequest;
import java.awt.CardLayout;
import java.awt.Image;
import java.io.File;
import java.util.ArrayList;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author anush
 */
public class BuyerRegistrationFormJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private EcoSystem system;
    private UserAccount useraccount;
    private Property property;
    private PropertyDirectory propertyDirectory;
    private Network network;
    private Organization organization;
    private String imagePath;

    public BuyerRegistrationFormJPanel(JPanel userProcess, Organization organization, Network network, Enterprise enterprise, Property property, EcoSystem system, UserAccount useraccount) {
        initComponents();
        this.userProcessContainer = userProcess;
        this.useraccount = useraccount;
        this.system = system;
        this.property = property;
        this.propertyDirectory = (system.getPropertyDirectory() == null) ? new PropertyDirectory() : system.getPropertyDirectory();
        this.network = network;
        this.organization = organization;
        txtHouse.setText(property.getPropertyName());
    }
    public ImageIcon ResizeImage(String ImagePath) {
        ImageIcon MyImage = new ImageIcon(ImagePath);
        Image img = MyImage.getImage();
        Image newImg = img.getScaledInstance(imgupload.getWidth(), imgupload.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImg);
        return image;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        uploadlbl = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtId = new javax.swing.JTextField();
        btnUpload = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        btnsubmit = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtZipcode = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtHouse = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btnBack1 = new javax.swing.JButton();
        applyForLoan = new javax.swing.JCheckBox();
        fileNameLabel = new javax.swing.JLabel();
        imgupload = new javax.swing.JLabel();

        setBackground(new java.awt.Color(241, 241, 242));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel1.setText("Name:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 158, -1, -1));

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel2.setText("Phone:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 208, -1, -1));

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel3.setText("Address");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 255, -1, -1));

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel4.setText("Email:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 355, -1, -1));

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel5.setText("NationalID");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 402, -1, -1));
        add(uploadlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(518, 828, 288, -1));
        add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 159, 140, -1));
        add(txtPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 209, 140, -1));
        add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 256, 140, -1));
        add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 356, 140, -1));
        add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 403, 140, -1));

        btnUpload.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnUpload.setText("Upload ID document");
        btnUpload.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUpload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUploadActionPerformed(evt);
            }
        });
        add(btnUpload, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 450, -1, 25));
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 779, -1, -1));

        btnsubmit.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnsubmit.setText("Submit");
        btnsubmit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnsubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsubmitActionPerformed(evt);
            }
        });
        add(btnsubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 670, -1, -1));

        jLabel8.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel8.setText("REGISTRATION FORM");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 60, -1, 37));

        jLabel9.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel9.setText("Zipcode");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 306, -1, -1));
        add(txtZipcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 307, 140, -1));

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel6.setText("Selected House");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 560, -1, 27));

        txtHouse.setEnabled(false);
        add(txtHouse, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 560, 127, 27));

        jLabel10.setBackground(new java.awt.Color(204, 204, 204));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon_new/house5.png"))); // NOI18N
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 110, 470, 530));
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 514, 269, -1));

        btnBack1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon_new/back.png"))); // NOI18N
        btnBack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack1ActionPerformed(evt);
            }
        });
        add(btnBack1, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 30, 30, 30));

        applyForLoan.setText("Apply For Government Loan");
        applyForLoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applyForLoanActionPerformed(evt);
            }
        });
        add(applyForLoan, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 610, -1, -1));

        fileNameLabel.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        fileNameLabel.setForeground(new java.awt.Color(25, 56, 82));
        add(fileNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 490, 270, 20));
        add(imgupload, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 410, 300, 140));
    }// </editor-fold>//GEN-END:initComponents

    private void btnsubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsubmitActionPerformed
        // TODO add your handling code here:
        String name = txtname.getText();
        String phone = txtPhone.getText();
        String address = txtAddress.getText();
        String zipcode = txtZipcode.getText();
        String email = txtEmail.getText();
        String nationalId = txtId.getText();
        String idDoc = imagePath;
        Boolean applyLoan = applyForLoan.isSelected();

        if (name.isEmpty() || address.isEmpty() || phone.isEmpty() || zipcode.isEmpty() || nationalId.isEmpty() || email.isEmpty() || idDoc.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter the missing field to continue!");
        }else if(!system.isInt(txtZipcode.getText()) || txtZipcode.getText().length() != 5){
            JOptionPane.showMessageDialog(null, "Please enter valid 5 digit zipcode!");
            return;
        }else if(!system.checkValidPhoneFormat(txtPhone.getText())){
            return;
        }else if(!system.checkValidEmailFormat(txtEmail.getText())){
            return;
        }else if(!system.checkIfEmailIsUnique(txtEmail.getText(), useraccount.getUsername())){
            return;
        }else if(!system.checkIfPhoneIsUnique(txtPhone.getText(), useraccount.getUsername())){
            return;
        } else if (!system.isInt(txtZipcode.getText()) || txtZipcode.getText().length() != 5) {
            JOptionPane.showMessageDialog(null, "Please enter valid 5 digit zipcode!");
            return;
        } else {
            useraccount.setName(name);
            useraccount.setPhone(phone);
            useraccount.setEmail(email);
            useraccount.setStreet(address);
            useraccount.setZipcode(zipcode);
            useraccount.setNationId(nationalId);
            useraccount.setIdDoc(idDoc);
            ArrayList<UserAccount> registeredBuyer = property.getRegisteredBuyer();
            registeredBuyer.add(useraccount);
            property.setRegisteredBuyer(registeredBuyer);
            if (applyLoan) {
                for (Enterprise e : network.getEnterpriseDirectory().getEnterpriseList()) {
                    for (Organization org : e.getOrganizationDirectory().getOrganizationList()) {
                        if (org.getType() == Organization.Type.Goverment) {
                            GovtEmpRequest cr = new GovtEmpRequest();
                            cr.setRequestID();
                            cr.setBuyer(useraccount);
                            cr.setSeller(property.getSeller());
                            cr.setStatus("Pending");
                            cr.setProperty(property);
                            e.getWorkQueue().getWorkRequestList().add(cr);
                            JOptionPane.showMessageDialog(null, "Request Sent Successfully!");
                        }
                    }
                }
            }
            JOptionPane.showMessageDialog(this, "Thank you for submitting the form!");
        }
    }//GEN-LAST:event_btnsubmitActionPerformed

    private void btnUploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUploadActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        int result = fileChooser.showSaveDialog(null);
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            imagePath = selectedFile.getAbsolutePath();
            String regex
                    = "([^\\s]+(\\.(?i)(jpe?g|png|gif|bmp))$)";
            Pattern p = Pattern.compile(regex);
            Matcher m = p.matcher(imagePath);
            if (!m.matches()) {
                JOptionPane.showMessageDialog(null, "Please enter valid image file!");
                return;
            }
            fileNameLabel.setText(imagePath);
            displayImage(imagePath);
            JOptionPane.showMessageDialog(null, "Picture Uploaded Successfully");

        }
    }//GEN-LAST:event_btnUploadActionPerformed
    public void displayImage(String imgPath) {
        imgupload.setIcon(ResizeImage(imgPath));
    }
    private void btnBack1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack1ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBack1ActionPerformed

    private void applyForLoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applyForLoanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_applyForLoanActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox applyForLoan;
    private javax.swing.JButton btnBack1;
    private javax.swing.JButton btnUpload;
    private javax.swing.JButton btnsubmit;
    private javax.swing.JLabel fileNameLabel;
    private javax.swing.JLabel imgupload;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtHouse;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtZipcode;
    private javax.swing.JTextField txtname;
    private javax.swing.JLabel uploadlbl;
    // End of variables declaration//GEN-END:variables
}
