/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SellerRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Property.Property;
import Business.Property.PropertyDirectory;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Dinesh
 */
public class CreateAdvertiseJPanel extends javax.swing.JPanel {

    JFileChooser imgChooser;
    private final EcoSystem system;
    private final UserAccount userAccount;
    BufferedImage img;
    private final JPanel userProcessContainer;
    private final Enterprise enterprise;
    private final PropertyDirectory propertyDirectory;
    private String imagePath;

    /**
     * Creates new form CreateAdvertiseJPanel
     */
    public CreateAdvertiseJPanel(JPanel userProcessContainer, Enterprise enterprise, UserAccount useraccount, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.userAccount = useraccount;
        this.system = system;
        this.propertyDirectory = (system.getPropertyDirectory() == null) ? new PropertyDirectory() : system.getPropertyDirectory();
        disableLabels();
    }

    public ImageIcon ResizeImage(String ImagePath) {
        ImageIcon MyImage = new ImageIcon(ImagePath);
        Image img = MyImage.getImage();
        Image newImg = img.getScaledInstance(imgupload.getWidth(), imgupload.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImg);
        return image;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        nameTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cityTxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        addressTxt = new javax.swing.JTextField();
        stateTxt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        longitudeTxt = new javax.swing.JTextField();
        submitBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        uploadBtn = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        bhkTxt = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        priceTxt = new javax.swing.JTextField();
        imgupload = new javax.swing.JLabel();
        zipcodeTxt = new javax.swing.JTextField();
        homeNamelbl = new javax.swing.JLabel();
        imglbl = new javax.swing.JLabel();
        bhklbl = new javax.swing.JLabel();
        pricelbl = new javax.swing.JLabel();
        bathroomlbl = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        latitudeTxt = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        bathroomTxt = new javax.swing.JTextField();
        longitudelbl = new javax.swing.JLabel();
        latitudelbl = new javax.swing.JLabel();
        fileNameLabel = new javax.swing.JLabel();
        btnBack1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(241, 241, 242));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(241, 241, 242));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(nameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 180, -1));

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        jLabel2.setText("Name* :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, -1, -1));

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        jLabel3.setText("City");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, -1, -1));
        jPanel1.add(cityTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 180, -1));

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        jLabel6.setText("House Address:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 110, -1, -1));

        addressTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressTxtActionPerformed(evt);
            }
        });
        jPanel1.add(addressTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 110, 180, -1));
        jPanel1.add(stateTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 180, 180, -1));

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        jLabel7.setText("State");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 180, -1, -1));

        jLabel8.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        jLabel8.setText("Upload Image* :");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 250, -1, -1));

        jLabel10.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        jLabel10.setText("BHK:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, -1, -1));

        longitudeTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                longitudeTxtActionPerformed(evt);
            }
        });
        jPanel1.add(longitudeTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 450, 180, -1));

        submitBtn.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        submitBtn.setText("Save");
        submitBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        submitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBtnActionPerformed(evt);
            }
        });
        jPanel1.add(submitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 570, 105, 40));

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        jLabel4.setText("Pincode:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, -1, -1));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(25, 56, 82));
        jLabel11.setText("HOUSE ADVERTISEMENT");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, -1, -1));

        uploadBtn.setBackground(new java.awt.Color(255, 255, 255));
        uploadBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        uploadBtn.setText("Choose..");
        uploadBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadBtnActionPerformed(evt);
            }
        });
        jPanel1.add(uploadBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 240, -1, -1));

        jLabel12.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        jLabel12.setText("Longitude:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 450, -1, -1));
        jPanel1.add(bhkTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, 180, -1));

        jLabel13.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        jLabel13.setText("Rent:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 510, -1, -1));
        jPanel1.add(priceTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 500, 180, -1));
        jPanel1.add(imgupload, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 210, 300, 140));
        jPanel1.add(zipcodeTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, 180, -1));

        homeNamelbl.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        homeNamelbl.setForeground(new java.awt.Color(255, 0, 0));
        homeNamelbl.setText("Please enter the name");
        jPanel1.add(homeNamelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 220, 20));

        imglbl.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        imglbl.setForeground(new java.awt.Color(255, 51, 51));
        imglbl.setText("Please upload the image of the house ");
        jPanel1.add(imglbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 280, 200, -1));

        bhklbl.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        bhklbl.setForeground(new java.awt.Color(255, 51, 51));
        bhklbl.setText("Please enter BHK value in integers");
        jPanel1.add(bhklbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, 210, -1));

        pricelbl.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        pricelbl.setForeground(new java.awt.Color(255, 51, 51));
        pricelbl.setText("Please enter price in 0.0 format");
        jPanel1.add(pricelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 540, 200, -1));

        bathroomlbl.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        bathroomlbl.setForeground(new java.awt.Color(255, 51, 51));
        bathroomlbl.setText("Enter the bathroom in number format");
        jPanel1.add(bathroomlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 390, 190, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon_new/house4.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, -1, -1));
        jPanel1.add(latitudeTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 400, 180, -1));

        jLabel14.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        jLabel14.setText("Latitude:");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 410, -1, -1));

        jLabel15.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        jLabel15.setText("Bathroom:");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 360, -1, -1));
        jPanel1.add(bathroomTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 360, 180, -1));

        longitudelbl.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        longitudelbl.setForeground(new java.awt.Color(255, 51, 51));
        longitudelbl.setText("Please enter longitude in 0.0 format");
        jPanel1.add(longitudelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 490, 200, -1));

        latitudelbl.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        latitudelbl.setForeground(new java.awt.Color(255, 51, 51));
        latitudelbl.setText("Please enter latitude in 0.0 format");
        jPanel1.add(latitudelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 450, 200, -1));

        fileNameLabel.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        fileNameLabel.setForeground(new java.awt.Color(25, 56, 82));
        jPanel1.add(fileNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 300, 330, 20));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 1280, 680));

        btnBack1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon_new/back.png"))); // NOI18N
        btnBack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack1ActionPerformed(evt);
            }
        });
        add(btnBack1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 20, 30, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void uploadBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadBtnActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        int result = fileChooser.showSaveDialog(null);
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            imagePath = selectedFile.getAbsolutePath();
            String regex
                    = "([^\\s]+(\\.(?i)(jpe?g|png|gif|bmp))$)";
            Pattern p = Pattern.compile(regex);
            Matcher m = p.matcher(imagePath);
            if (!m.matches()) {
                JOptionPane.showMessageDialog(null, "Please enter valid image file!");
                return;
            }
            fileNameLabel.setText(imagePath);
            displayImage(imagePath);
            JOptionPane.showMessageDialog(null, "Picture Uploaded Successfully");

        }
    }//GEN-LAST:event_uploadBtnActionPerformed

    public void displayImage(String imgPath) {
        imgupload.setIcon(ResizeImage(imgPath));
    }
    private void addressTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressTxtActionPerformed

    private void submitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBtnActionPerformed
        // TODO add your handling code here:
        String name = nameTxt.getText();
        String address = addressTxt.getText();
        String city = cityTxt.getText();
        String state = stateTxt.getText();
        String pincode = zipcodeTxt.getText();
        Double price = Double.parseDouble((priceTxt.getText()).isEmpty() ? "0.0" : priceTxt.getText());
        int bhk = Integer.parseInt((bhkTxt.getText()).isEmpty() ? "0" : bhkTxt.getText());
        Double bathroom = Double.parseDouble((bathroomTxt.getText()).isEmpty() ? "0.0" : bathroomTxt.getText());
        Double latitude = Double.parseDouble((latitudeTxt.getText()).isEmpty() ? "0.0" : latitudeTxt.getText());
        Double longitude = Double.parseDouble((longitudeTxt.getText()).isEmpty() ? "0.0" : longitudeTxt.getText());
        ImageIcon img = (ImageIcon) imgupload.getIcon();

        if (name.isEmpty() || address.isEmpty() || city.isEmpty() || state.isEmpty() || pincode.isEmpty()
                || priceTxt.getText().isEmpty() || img == null || bathroomTxt.getText().isEmpty()
                || longitudeTxt.getText().isEmpty() || latitudeTxt.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter all the fields continue!");
        } else if (!system.isDouble(priceTxt.getText())) {
            pricelbl.setVisible(true);
            JOptionPane.showMessageDialog(null, "Please enter valid rent!");
        } else if (!system.isDouble(bathroomTxt.getText())) {
            bathroomlbl.setVisible(true);
            JOptionPane.showMessageDialog(null, "Please enter valid bathroom value!");
        } else if (!system.isDouble(longitudeTxt.getText())) {
            longitudelbl.setVisible(true);
            JOptionPane.showMessageDialog(null, "Please enter valid longitude!");
        } else if (!system.isDouble(latitudeTxt.getText())) {
            latitudelbl.setVisible(true);
            JOptionPane.showMessageDialog(null, "Please enter valid latitude!");
        } else if (!system.isInt(bhkTxt.getText())) {
            bhklbl.setVisible(true);
            JOptionPane.showMessageDialog(null, "Please enter valid bhk value!");
        } else if (!system.isInt(zipcodeTxt.getText()) || zipcodeTxt.getText().length() != 5) {
            JOptionPane.showMessageDialog(null, "Please enter valid 5 digit zipcode!");
        } else {
            disableLabels();
            Property property = new Property();
            property.setPropertyName(name);
            property.setStreet(address);
            property.setPincode(pincode);
            property.setCity(city);
            property.setState(state);
            property.setBhk(bhk);
            property.setBathroom(bathroom);
            property.setPrice(price);
            property.setStatus("Vacant");
            property.setUploadImg(imagePath);
            property.setSeller(userAccount);
            property.setPropertyID(propertyDirectory.generatePropertyID());
            property.setLatitude(latitude);
            property.setLongitude(longitude);
            propertyDirectory.addProperty(property);
            system.setPropertyDirectory(propertyDirectory);
            JOptionPane.showMessageDialog(null, "Advertisement Added!");
            emptyAllFields();
        }
    }//GEN-LAST:event_submitBtnActionPerformed

    private void longitudeTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_longitudeTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_longitudeTxtActionPerformed

    private void btnBack1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack1ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBack1ActionPerformed

    public void emptyAllFields() {
        nameTxt.setText("");
        addressTxt.setText("");
        cityTxt.setText("");
        stateTxt.setText("");
        zipcodeTxt.setText("");
        imgupload.setText("");
        priceTxt.setText("");
        bhkTxt.setText("");
        bathroomTxt.setText("");
        latitudeTxt.setText("");
        longitudeTxt.setText("");
    }

    public void disableLabels() {
        homeNamelbl.setVisible(false);
        bhklbl.setVisible(false);
        imglbl.setVisible(false);
        pricelbl.setVisible(false);
        bathroomlbl.setVisible(false);
        latitudelbl.setVisible(false);
        longitudelbl.setVisible(false);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressTxt;
    private javax.swing.JTextField bathroomTxt;
    private javax.swing.JLabel bathroomlbl;
    private javax.swing.JTextField bhkTxt;
    private javax.swing.JLabel bhklbl;
    private javax.swing.JButton btnBack1;
    private javax.swing.JTextField cityTxt;
    private javax.swing.JLabel fileNameLabel;
    private javax.swing.JLabel homeNamelbl;
    private javax.swing.JLabel imglbl;
    private javax.swing.JLabel imgupload;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField latitudeTxt;
    private javax.swing.JLabel latitudelbl;
    private javax.swing.JTextField longitudeTxt;
    private javax.swing.JLabel longitudelbl;
    private javax.swing.JTextField nameTxt;
    private javax.swing.JTextField priceTxt;
    private javax.swing.JLabel pricelbl;
    private javax.swing.JTextField stateTxt;
    private javax.swing.JButton submitBtn;
    private javax.swing.JButton uploadBtn;
    private javax.swing.JTextField zipcodeTxt;
    // End of variables declaration//GEN-END:variables
}
