package userinterface.SellerRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Charmi
 */
public class SellerWorkAreaJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    Enterprise enterprise;
    EcoSystem system;
    Network network;
    UserAccount account;
    Organization organization;

    /**
     * Creates new form AdminWorkAreaJPanel
     */
    public SellerWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, Organization organization, Enterprise enterprise, Network network, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.system = business;
        this.network = network;
        this.enterprise = enterprise;
        this.organization = organization;
        manageAdvertise();

    }

    private void manageAdvertise() {
        CreateAdvertiseJPanel advrtPanel = new CreateAdvertiseJPanel(rightSystemAdminPanel, enterprise, account, system);
        rightSystemAdminPanel.add("advrtPanel", advrtPanel);
        CardLayout layout = (CardLayout) rightSystemAdminPanel.getLayout();
        layout.next(rightSystemAdminPanel);
    }

    private void manageHouses() {
        ManageHouseJPanel mngHousesPanel = new ManageHouseJPanel(rightSystemAdminPanel, enterprise, account, system);
        rightSystemAdminPanel.add("ManageHouseJPanel", mngHousesPanel);
        CardLayout layout = (CardLayout) rightSystemAdminPanel.getLayout();
        layout.next(rightSystemAdminPanel);
    }

    private void manageProfile() {
        ManageSellerProfileJPanel manageSellerProfileJPanel = new ManageSellerProfileJPanel(rightSystemAdminPanel, system, account);
        rightSystemAdminPanel.add("ManageInspectorJPanel", manageSellerProfileJPanel);
        CardLayout layout = (CardLayout) rightSystemAdminPanel.getLayout();
        layout.next(rightSystemAdminPanel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        systemAdminPanel = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        manageAdvertisePanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        manageAdvertise = new javax.swing.JLabel();
        manageSellerProfile = new javax.swing.JPanel();
        manageProfile = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        manageHousesJpanel = new javax.swing.JPanel();
        manageHouses = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        manageHousesPanel = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        rightSystemAdminPanel = new javax.swing.JPanel();

        setPreferredSize(new java.awt.Dimension(1338, 840));
        setLayout(new java.awt.BorderLayout());

        systemAdminPanel.setBackground(new java.awt.Color(241, 241, 242));
        systemAdminPanel.setMinimumSize(new java.awt.Dimension(1338, 840));
        systemAdminPanel.setPreferredSize(new java.awt.Dimension(1338, 840));

        jPanel3.setBackground(new java.awt.Color(255, 213, 90));
        jPanel3.setMinimumSize(new java.awt.Dimension(280, 840));
        jPanel3.setPreferredSize(new java.awt.Dimension(280, 840));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        manageAdvertisePanel.setBackground(new java.awt.Color(255, 213, 90));
        manageAdvertisePanel.setToolTipText("");
        manageAdvertisePanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        manageAdvertisePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                manageAdvertisePanelMousePressed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(255, 213, 90));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon_new/best.png"))); // NOI18N
        jLabel2.setToolTipText("");

        manageAdvertise.setBackground(new java.awt.Color(255, 213, 90));
        manageAdvertise.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        manageAdvertise.setText("Create Advertise");
        manageAdvertise.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        manageAdvertise.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                manageAdvertiseMousePressed(evt);
            }
        });

        javax.swing.GroupLayout manageAdvertisePanelLayout = new javax.swing.GroupLayout(manageAdvertisePanel);
        manageAdvertisePanel.setLayout(manageAdvertisePanelLayout);
        manageAdvertisePanelLayout.setHorizontalGroup(
            manageAdvertisePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manageAdvertisePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(manageAdvertise, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        manageAdvertisePanelLayout.setVerticalGroup(
            manageAdvertisePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, manageAdvertisePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(manageAdvertisePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(manageAdvertise, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel3.add(manageAdvertisePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 280, 50));

        manageSellerProfile.setBackground(new java.awt.Color(255, 213, 90));
        manageSellerProfile.setToolTipText("");
        manageSellerProfile.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        manageSellerProfile.setPreferredSize(new java.awt.Dimension(264, 48));
        manageSellerProfile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                manageSellerProfileMousePressed(evt);
            }
        });

        manageProfile.setBackground(new java.awt.Color(255, 213, 90));
        manageProfile.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        manageProfile.setText("Manage Profile");
        manageProfile.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        manageProfile.setPreferredSize(new java.awt.Dimension(115, 16));

        jLabel6.setBackground(new java.awt.Color(255, 213, 90));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon_new/manager24x.png"))); // NOI18N

        javax.swing.GroupLayout manageSellerProfileLayout = new javax.swing.GroupLayout(manageSellerProfile);
        manageSellerProfile.setLayout(manageSellerProfileLayout);
        manageSellerProfileLayout.setHorizontalGroup(
            manageSellerProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, manageSellerProfileLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(manageProfile, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                .addContainerGap())
        );
        manageSellerProfileLayout.setVerticalGroup(
            manageSellerProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, manageSellerProfileLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(manageSellerProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(manageProfile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel3.add(manageSellerProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 280, 40));

        manageHousesJpanel.setBackground(new java.awt.Color(255, 213, 90));
        manageHousesJpanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        manageHousesJpanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                manageHousesJpanelMousePressed(evt);
            }
        });

        manageHouses.setBackground(new java.awt.Color(255, 213, 90));
        manageHouses.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        manageHouses.setText("Manage Houses");
        manageHouses.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        manageHouses.setPreferredSize(new java.awt.Dimension(115, 16));
        manageHouses.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                manageHousesMousePressed(evt);
            }
        });

        jLabel7.setBackground(new java.awt.Color(255, 213, 90));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon_new/icons8-houses-48.png"))); // NOI18N

        javax.swing.GroupLayout manageHousesJpanelLayout = new javax.swing.GroupLayout(manageHousesJpanel);
        manageHousesJpanel.setLayout(manageHousesJpanelLayout);
        manageHousesJpanelLayout.setHorizontalGroup(
            manageHousesJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, manageHousesJpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(manageHouses, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        manageHousesJpanelLayout.setVerticalGroup(
            manageHousesJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(manageHouses, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel3.add(manageHousesJpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 280, 50));

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel3.setText("SELLER WORK AREA ");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jPanel3.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 30, 320, 20));

        manageHousesPanel.setBackground(new java.awt.Color(255, 213, 90));
        manageHousesPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                manageHousesPanelMousePressed(evt);
            }
        });

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout manageHousesPanelLayout = new javax.swing.GroupLayout(manageHousesPanel);
        manageHousesPanel.setLayout(manageHousesPanelLayout);
        manageHousesPanelLayout.setHorizontalGroup(
            manageHousesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, manageHousesPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        manageHousesPanelLayout.setVerticalGroup(
            manageHousesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, manageHousesPanelLayout.createSequentialGroup()
                .addGap(0, 28, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel3.add(manageHousesPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 280, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon_new/estate-agent.png"))); // NOI18N
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, 200));

        rightSystemAdminPanel.setBackground(new java.awt.Color(241, 241, 242));
        rightSystemAdminPanel.setPreferredSize(new java.awt.Dimension(1058, 840));
        rightSystemAdminPanel.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout systemAdminPanelLayout = new javax.swing.GroupLayout(systemAdminPanel);
        systemAdminPanel.setLayout(systemAdminPanelLayout);
        systemAdminPanelLayout.setHorizontalGroup(
            systemAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(systemAdminPanelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(rightSystemAdminPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        systemAdminPanelLayout.setVerticalGroup(
            systemAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rightSystemAdminPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(systemAdminPanelLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        add(systemAdminPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void manageAdvertiseMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageAdvertiseMousePressed
        manageAdvertise();
    }//GEN-LAST:event_manageAdvertiseMousePressed

    private void manageAdvertisePanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageAdvertisePanelMousePressed
        // TODO add your handling code here:
        manageAdvertise();
    }//GEN-LAST:event_manageAdvertisePanelMousePressed

    private void manageSellerProfileMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageSellerProfileMousePressed
        // TODO add your handling code here:
        manageProfile();
    }//GEN-LAST:event_manageSellerProfileMousePressed

    private void manageHousesJpanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageHousesJpanelMousePressed
        manageHouses();
    }//GEN-LAST:event_manageHousesJpanelMousePressed

    private void manageHousesPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageHousesPanelMousePressed
        // TODO add your handling code here:
        manageHouses();
    }//GEN-LAST:event_manageHousesPanelMousePressed

    private void manageHousesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageHousesMousePressed
        // TODO add your handling code here:
        manageHouses();

    }//GEN-LAST:event_manageHousesMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel manageAdvertise;
    private javax.swing.JPanel manageAdvertisePanel;
    private javax.swing.JLabel manageHouses;
    private javax.swing.JPanel manageHousesJpanel;
    private javax.swing.JPanel manageHousesPanel;
    private javax.swing.JLabel manageProfile;
    private javax.swing.JPanel manageSellerProfile;
    private javax.swing.JPanel rightSystemAdminPanel;
    private javax.swing.JPanel systemAdminPanel;
    // End of variables declaration//GEN-END:variables

}
