

package userinterface.PlumberRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * @author  anusha
 */
public class PlumberWorkAreaJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    Enterprise enterprise;
    EcoSystem system;
    Network network;
    UserAccount account;
    Organization organization;

    /**
     * Creates new form AdminWorkAreaJPanel
     */
    public PlumberWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, Organization organization, Enterprise enterprise, Network network, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.system = business;
        this.network = network;
        this.enterprise = enterprise;
        this.organization = organization;
        manageJobs();

    }

    private void manageJobs() {
        
        ViewJobJPanel viewJobsJPanel = new ViewJobJPanel(userRight, enterprise, account, system);
        userRight.add("viewJobsJPanel",viewJobsJPanel);
        CardLayout layout = (CardLayout) userRight.getLayout();
        layout.next(userRight);
    }

    private void manageProfile() {
        
        ManagePlumberJPanel manageProfileJPanel = new ManagePlumberJPanel(userRight, enterprise, account, system);
        userRight.add("manageProfileJPanel", manageProfileJPanel);
        CardLayout layout = (CardLayout) userRight.getLayout();
        layout.next(userRight);
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        systemAdminPanel = new javax.swing.JPanel();
        userLeft = new javax.swing.JPanel();
        manageProfilePanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        manageProfile = new javax.swing.JLabel();
        manageJobsPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        manageJobs = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        userRight = new javax.swing.JPanel();

        setPreferredSize(new java.awt.Dimension(1338, 840));
        setLayout(new java.awt.BorderLayout());

        systemAdminPanel.setBackground(new java.awt.Color(241, 241, 242));
        systemAdminPanel.setMinimumSize(new java.awt.Dimension(1338, 840));
        systemAdminPanel.setPreferredSize(new java.awt.Dimension(1338, 840));

        userLeft.setBackground(new java.awt.Color(255, 213, 90));
        userLeft.setMinimumSize(new java.awt.Dimension(280, 840));
        userLeft.setPreferredSize(new java.awt.Dimension(280, 840));
        userLeft.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        manageProfilePanel.setBackground(new java.awt.Color(255, 213, 90));
        manageProfilePanel.setToolTipText("");
        manageProfilePanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        manageProfilePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                manageProfilePanelMousePressed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(255, 213, 90));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon_new/management.png"))); // NOI18N
        jLabel2.setToolTipText("");

        manageProfile.setBackground(new java.awt.Color(255, 213, 90));
        manageProfile.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        manageProfile.setText("Manage Profile");
        manageProfile.setAutoscrolls(true);
        manageProfile.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        manageProfile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                manageProfileMousePressed(evt);
            }
        });

        javax.swing.GroupLayout manageProfilePanelLayout = new javax.swing.GroupLayout(manageProfilePanel);
        manageProfilePanel.setLayout(manageProfilePanelLayout);
        manageProfilePanelLayout.setHorizontalGroup(
            manageProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manageProfilePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(manageProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
        );
        manageProfilePanelLayout.setVerticalGroup(
            manageProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manageProfilePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(manageProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(manageProfilePanelLayout.createSequentialGroup()
                        .addComponent(manageProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE))
                .addContainerGap())
        );

        userLeft.add(manageProfilePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 280, -1));

        manageJobsPanel.setBackground(new java.awt.Color(255, 213, 90));
        manageJobsPanel.setToolTipText("");
        manageJobsPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        manageJobsPanel.setPreferredSize(new java.awt.Dimension(264, 48));
        manageJobsPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                manageJobsPanelMousePressed(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(255, 213, 90));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon_new/request.png"))); // NOI18N

        manageJobs.setBackground(new java.awt.Color(255, 213, 90));
        manageJobs.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        manageJobs.setText("Manage Jobs");
        manageJobs.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        manageJobs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                manageJobsMousePressed(evt);
            }
        });

        javax.swing.GroupLayout manageJobsPanelLayout = new javax.swing.GroupLayout(manageJobsPanel);
        manageJobsPanel.setLayout(manageJobsPanelLayout);
        manageJobsPanelLayout.setHorizontalGroup(
            manageJobsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manageJobsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(manageJobs, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                .addContainerGap())
        );
        manageJobsPanelLayout.setVerticalGroup(
            manageJobsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(manageJobs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        userLeft.add(manageJobsPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 280, 40));

        jSeparator1.setBackground(new java.awt.Color(255, 213, 90));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        userLeft.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 280, 70));

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel3.setText("PLUMBER  MANAGEMENT");
        userLeft.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, -1, 190, 30));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        userLeft.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 280, 20));

        userRight.setBackground(new java.awt.Color(241, 241, 242));
        userRight.setPreferredSize(new java.awt.Dimension(1058, 840));
        userRight.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout systemAdminPanelLayout = new javax.swing.GroupLayout(systemAdminPanel);
        systemAdminPanel.setLayout(systemAdminPanelLayout);
        systemAdminPanelLayout.setHorizontalGroup(
            systemAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(systemAdminPanelLayout.createSequentialGroup()
                .addComponent(userLeft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userRight, javax.swing.GroupLayout.PREFERRED_SIZE, 1210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        systemAdminPanelLayout.setVerticalGroup(
            systemAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(userRight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(systemAdminPanelLayout.createSequentialGroup()
                .addComponent(userLeft, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        add(systemAdminPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void manageJobsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageJobsMousePressed
        manageJobs();
    }//GEN-LAST:event_manageJobsMousePressed

    private void manageProfilePanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageProfilePanelMousePressed
        // TODO add your handling code here:
        manageProfile();
    }//GEN-LAST:event_manageProfilePanelMousePressed

    private void manageProfileMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageProfileMousePressed
        manageProfile();
    }//GEN-LAST:event_manageProfileMousePressed

    private void manageJobsPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageJobsPanelMousePressed
        // TODO add your handling code here:
       manageJobs();
    }//GEN-LAST:event_manageJobsPanelMousePressed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel manageJobs;
    private javax.swing.JPanel manageJobsPanel;
    private javax.swing.JLabel manageProfile;
    private javax.swing.JPanel manageProfilePanel;
    private javax.swing.JPanel systemAdminPanel;
    private javax.swing.JPanel userLeft;
    private javax.swing.JPanel userRight;
    // End of variables declaration//GEN-END:variables
    
}
