/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.BuyerRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.Property.Property;
import Business.Property.PropertyDirectory;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.AgentRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;

/**
 *
 * @author Dinesh
 */
public class ManageAgentActivity extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private EcoSystem system;
    private UserAccount userAccount;
    private PropertyDirectory propertyDirectory;
    private Enterprise enterprise;
    private Network network;
    private Organization organization;

    /**
     * Creates new form ViewCleanerJobs
     */
    public ManageAgentActivity(JPanel userProcess, UserAccount userAccount, EcoSystem system, Enterprise enterprise, Network network, Organization organization) {
        initComponents();
        this.userProcessContainer = userProcess;
        this.system = system;
        this.userAccount = userAccount;
        this.enterprise = enterprise;
        this.network = network;
        this.organization = organization;
        this.propertyDirectory = (system.getPropertyDirectory() == null) ? new PropertyDirectory() : system.getPropertyDirectory();
        jtblHouse.setVisible(false);
        populateRequestTable();
    }

    public void populateRequestTable() {
        DefaultTableModel model = (DefaultTableModel) houseTable.getModel();
        model.setRowCount(0);
        for (Network n : system.getNetworkList()) {
            for (Enterprise e : n.getEnterpriseDirectory().getEnterpriseList()) {
                if (e.getEnterpriseType() == Enterprise.EnterpriseType.Broker) {
                    for (WorkRequest workRequest : e.getWorkQueue().getWorkRequestList()) {
                        if (workRequest instanceof AgentRequest) {
                            if (userAccount.getUsername().equals(((AgentRequest) workRequest).getBuyer().getUsername())) {
                                Object[] row = new Object[model.getColumnCount()];
                                row[0] = ((AgentRequest) workRequest);
                                row[1] = ((AgentRequest) workRequest).getAgent().getName();
                                row[2] = ((AgentRequest) workRequest).getSeller().getName();
                                row[3] = ((AgentRequest) workRequest).getProperty().getStreet();
                                row[4] = ((AgentRequest) workRequest).getProperty().getCity();
                                row[5] = ((AgentRequest) workRequest).getProperty().getState();
                                row[6] = ((AgentRequest) workRequest).getProperty().getPincode();
                                row[7] = ((AgentRequest) workRequest).getStatus();
                                row[8] = ((AgentRequest) workRequest).getBuyerNote();
                                row[9] = ((AgentRequest) workRequest).getInspectorNote();
                                row[10] = ((AgentRequest) workRequest).getAgent().getCharge();
                                row[11] = ((AgentRequest) workRequest).getQuote();
                                row[12] = ((AgentRequest) workRequest).getOrgType();
                                model.addRow(row);
                            }
                        }
                    }
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        houseTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtFeedback = new javax.swing.JTextField();
        btnCompleteJob = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnBack3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jhousebtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblHouse = new javax.swing.JTable();

        setBackground(new java.awt.Color(241, 241, 242));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        houseTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "JobID", "Agent", "Seller", "Street", "City", "State", "Zipcode", "Status", "Buyer Message", "Agent Message", "Charge", "Quote", "OrgType"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(houseTable);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 960, 270));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 51));
        jLabel1.setText("Feedback:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, -1, -1));
        add(txtFeedback, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 380, 245, -1));

        btnCompleteJob.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnCompleteJob.setForeground(new java.awt.Color(0, 0, 51));
        btnCompleteJob.setText("Send Message");
        btnCompleteJob.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCompleteJob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompleteJobActionPerformed(evt);
            }
        });
        add(btnCompleteJob, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 140, 30));

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel3.setText("VIEW AGENT JOB LIST");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 30, -1, 30));

        btnBack3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon_new/back.png"))); // NOI18N
        btnBack3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBack3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack3ActionPerformed(evt);
            }
        });
        add(btnBack3, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 30, 30, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon_new/AGENT.png"))); // NOI18N
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 370, 145, 164));

        jhousebtn.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jhousebtn.setForeground(new java.awt.Color(41, 50, 80));
        jhousebtn.setText("See Suggested Houses");
        jhousebtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jhousebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jhousebtnActionPerformed(evt);
            }
        });
        add(jhousebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, 240, 30));

        jtblHouse.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "HouseID", " Name", " Address", "City", "State", "Zipcode", "BHK", "Bathroom", "Rate", "Status", "SoldTo", "SellerName"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtblHouse);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 630, 900, 280));
    }// </editor-fold>//GEN-END:initComponents

    private void btnCompleteJobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompleteJobActionPerformed
        // TODO add your handling code here:
        int selectedRow = houseTable.getSelectedRow();

        if (selectedRow >= 0) {
            AgentRequest br = (AgentRequest) houseTable.getValueAt(selectedRow, 0);
            String feedback = txtFeedback.getText();
            if (feedback.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Please enter valid & non empty value for feedback");
                return;
            }
            br.setBuyerNote(feedback);
            populateRequestTable();
            JOptionPane.showMessageDialog(null, "Message Sent Successfully!");

        } else {
            JOptionPane.showMessageDialog(null, "Please select one row!");
        }
    }//GEN-LAST:event_btnCompleteJobActionPerformed

    private void btnBack3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack3ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBack3ActionPerformed

    private void jhousebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jhousebtnActionPerformed
        // TODO add your handling code here:
        jtblHouse.setVisible(true);
        DefaultTableModel model = (DefaultTableModel) jtblHouse.getModel();
        model.setRowCount(0);
        int selectedRow = houseTable.getSelectedRow();

        if (selectedRow >= 0) {
            AgentRequest br = (AgentRequest) houseTable.getValueAt(selectedRow, 0);

            if (br instanceof AgentRequest) {
                ArrayList<String> propertyList = br.getPropertyList();
                if (propertyList.isEmpty()) {
                    JOptionPane.showMessageDialog(null, "Sorry there are no house suggestions yet!");
                    return;
                }
                for (String propertyID : propertyList) {
                    Property property = system.getPropertyDirectory().fetchProperty(propertyID);
                    Object[] row = new Object[model.getColumnCount()];
                    row[0] = property.getPropertyID();
                    row[1] = property.getPropertyName();
                    row[2] = property.getStreet();
                    row[3] = property.getCity();
                    row[4] = property.getState();
                    row[5] = property.getPincode();
                    row[6] = property.getBhk();
                    row[7] = property.getBathroom();
                    row[8] = property.getPrice();
                    row[9] = property.getStatus();
                    row[10] = property.getBuyer();
                    row[11] = property.getSeller();
                    model.addRow(row);
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please select one row!");
        }


    }//GEN-LAST:event_jhousebtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack3;
    private javax.swing.JButton btnCompleteJob;
    private javax.swing.JTable houseTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jhousebtn;
    private javax.swing.JTable jtblHouse;
    private javax.swing.JTextField txtFeedback;
    // End of variables declaration//GEN-END:variables
}
