

package userinterface.PackersMoversRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * @author  dinesh
 */
public class PackerWorkAreaJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    Enterprise enterprise;
    EcoSystem system;
    Network network;
    UserAccount account;
    Organization organization;

    /**
     * Creates new form AdminWorkAreaJPanel
     */
    public PackerWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, Organization organization, Enterprise enterprise, Network network, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.system = business;
        this.network = network;
        this.enterprise = enterprise;
        this.organization = organization;
        manageJobs();

    }

    private void manageJobs() {
      
        ViewDetailsJPanel viewJobsJPanel = new ViewDetailsJPanel(UserRight, enterprise, account, system);
        UserRight.add("viewJobsJPanel",viewJobsJPanel);
        CardLayout layout = (CardLayout) UserRight.getLayout();
        layout.next(UserRight);
    }

    private void manageProfile() {
      
        ManagePackerJPanel manageProfileJPanel = new ManagePackerJPanel(UserRight, enterprise, account, system);
        UserRight.add("managePackerProfileJPanel", manageProfileJPanel);
        CardLayout layout = (CardLayout) UserRight.getLayout();
        layout.next(UserRight);
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        systemAdminPanel = new javax.swing.JPanel();
        UserLeft = new javax.swing.JPanel();
        manageProfilePanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        manageProfileLabel = new javax.swing.JLabel();
        manageJobsPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        manageJobsLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        UserRight = new javax.swing.JPanel();

        setPreferredSize(new java.awt.Dimension(1338, 840));
        setLayout(new java.awt.BorderLayout());

        systemAdminPanel.setBackground(new java.awt.Color(241, 241, 242));
        systemAdminPanel.setMinimumSize(new java.awt.Dimension(1338, 840));
        systemAdminPanel.setPreferredSize(new java.awt.Dimension(1338, 840));

        UserLeft.setBackground(new java.awt.Color(255, 213, 90));
        UserLeft.setMinimumSize(new java.awt.Dimension(280, 840));
        UserLeft.setPreferredSize(new java.awt.Dimension(280, 840));
        UserLeft.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        manageProfilePanel.setBackground(new java.awt.Color(255, 213, 90));
        manageProfilePanel.setToolTipText("");
        manageProfilePanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        manageProfilePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                manageProfilePanelMousePressed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(255, 213, 90));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon_new/management.png"))); // NOI18N
        jLabel2.setToolTipText("");

        manageProfileLabel.setBackground(new java.awt.Color(255, 213, 90));
        manageProfileLabel.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        manageProfileLabel.setText("Manage Profile");
        manageProfileLabel.setAutoscrolls(true);
        manageProfileLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        manageProfileLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                manageProfileLabelMousePressed(evt);
            }
        });

        javax.swing.GroupLayout manageProfilePanelLayout = new javax.swing.GroupLayout(manageProfilePanel);
        manageProfilePanel.setLayout(manageProfilePanelLayout);
        manageProfilePanelLayout.setHorizontalGroup(
            manageProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manageProfilePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(manageProfileLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
        );
        manageProfilePanelLayout.setVerticalGroup(
            manageProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manageProfilePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(manageProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(manageProfilePanelLayout.createSequentialGroup()
                        .addComponent(manageProfileLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE))
                .addContainerGap())
        );

        UserLeft.add(manageProfilePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 280, -1));

        manageJobsPanel.setBackground(new java.awt.Color(255, 213, 90));
        manageJobsPanel.setToolTipText("");
        manageJobsPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        manageJobsPanel.setPreferredSize(new java.awt.Dimension(264, 48));
        manageJobsPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                manageJobsPanelMousePressed(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(255, 213, 90));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon_new/request.png"))); // NOI18N

        manageJobsLabel.setBackground(new java.awt.Color(255, 213, 90));
        manageJobsLabel.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        manageJobsLabel.setText("Manage Jobs");
        manageJobsLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        manageJobsLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                manageJobsLabelMousePressed(evt);
            }
        });

        javax.swing.GroupLayout manageJobsPanelLayout = new javax.swing.GroupLayout(manageJobsPanel);
        manageJobsPanel.setLayout(manageJobsPanelLayout);
        manageJobsPanelLayout.setHorizontalGroup(
            manageJobsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manageJobsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(manageJobsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                .addGap(6, 6, 6))
        );
        manageJobsPanelLayout.setVerticalGroup(
            manageJobsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(manageJobsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        UserLeft.add(manageJobsPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 280, 40));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        UserLeft.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 162, 290, 70));

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel3.setText("PACKER MANAGEMENT");
        UserLeft.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        UserLeft.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 190, 20));

        UserRight.setBackground(new java.awt.Color(241, 241, 242));
        UserRight.setPreferredSize(new java.awt.Dimension(1058, 840));
        UserRight.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout systemAdminPanelLayout = new javax.swing.GroupLayout(systemAdminPanel);
        systemAdminPanel.setLayout(systemAdminPanelLayout);
        systemAdminPanelLayout.setHorizontalGroup(
            systemAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(systemAdminPanelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(UserLeft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(UserRight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        systemAdminPanelLayout.setVerticalGroup(
            systemAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(UserRight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(systemAdminPanelLayout.createSequentialGroup()
                .addComponent(UserLeft, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        add(systemAdminPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void manageJobsLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageJobsLabelMousePressed
        manageJobs();
    }//GEN-LAST:event_manageJobsLabelMousePressed

    private void manageProfilePanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageProfilePanelMousePressed
        // TODO add your handling code here:
      manageProfile();  
    }//GEN-LAST:event_manageProfilePanelMousePressed

    private void manageProfileLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageProfileLabelMousePressed
        manageProfile();
    }//GEN-LAST:event_manageProfileLabelMousePressed

    private void manageJobsPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageJobsPanelMousePressed
        // TODO add your handling code here:
       manageJobs();
    }//GEN-LAST:event_manageJobsPanelMousePressed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel UserLeft;
    private javax.swing.JPanel UserRight;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel manageJobsLabel;
    private javax.swing.JPanel manageJobsPanel;
    private javax.swing.JLabel manageProfileLabel;
    private javax.swing.JPanel manageProfilePanel;
    private javax.swing.JPanel systemAdminPanel;
    // End of variables declaration//GEN-END:variables
    
}
