/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import Business.Airliner;
import Business.AirlinerDirectory;
import Business.CustomerDirectory;
import Business.FlightDirectory;
import UserInterface.Customer.CustomerDashboardJPanel;
import UserInterface.ManageAirliners.AirlinerCatalogue;
import UserInterface.MasterAirlinerFlightSchedule.airlinerFlightScheduleJPanel;
import UserInterface.ManageMasterFlightSchedule.masterFlightScheduleJPanel;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Charmi Dalal`
 */
public class AirlineAgencyMain extends javax.swing.JFrame {

    private CustomerDirectory dirCustomer;
    private AirlinerDirectory dirAirliner;
    private FlightDirectory dirFlight;

    public AirlineAgencyMain() {
        initComponents();
        this.dirAirliner = new AirlinerDirectory();
        this.dirCustomer = new CustomerDirectory();
        this.dirFlight = new FlightDirectory();
        showAirlinerComboBox();
    }

    public void showAirlinerComboBox() {
        ArrayList<String> airlinerList = new ArrayList();
        DefaultComboBoxModel comboModel = new DefaultComboBoxModel();
        comboModel.addElement("Select Airliner");
        for (Airliner airliner : dirAirliner.getAirlinerDir()) {
            if (!airlinerList.contains(airliner.getAirlineName())) {
                airlinerList.add(airliner.getAirlineName());
                comboModel.addElement(airliner.getAirlineName());
            }
        }
        airlinerComboBox.setModel(comboModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitPane = new javax.swing.JSplitPane();
        menuJPanel = new javax.swing.JPanel();
        airlinersBtn = new javax.swing.JButton();
        airlinerComboBox = new javax.swing.JComboBox<>();
        setFlightScheduleBtn = new javax.swing.JButton();
        travelAgencyBtn = new javax.swing.JButton();
        customerBtn = new javax.swing.JButton();
        cardLayoutJPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        airlinersBtn.setText("Airliners");
        airlinersBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                airlinersBtnActionPerformed(evt);
            }
        });

        airlinerComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                airlinerComboBoxActionPerformed(evt);
            }
        });

        setFlightScheduleBtn.setText("Set Flight Schedule");
        setFlightScheduleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setFlightScheduleBtnActionPerformed(evt);
            }
        });

        travelAgencyBtn.setText("Travel Agency");
        travelAgencyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                travelAgencyBtnActionPerformed(evt);
            }
        });

        customerBtn.setText("Customer");
        customerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuJPanelLayout = new javax.swing.GroupLayout(menuJPanel);
        menuJPanel.setLayout(menuJPanelLayout);
        menuJPanelLayout.setHorizontalGroup(
            menuJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menuJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(airlinerComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(airlinersBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(menuJPanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(setFlightScheduleBtn)
                        .addGap(0, 14, Short.MAX_VALUE))
                    .addComponent(customerBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(travelAgencyBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        menuJPanelLayout.setVerticalGroup(
            menuJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuJPanelLayout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(airlinersBtn)
                .addGap(57, 57, 57)
                .addComponent(airlinerComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(setFlightScheduleBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(customerBtn)
                .addGap(45, 45, 45)
                .addComponent(travelAgencyBtn)
                .addGap(187, 187, 187))
        );

        splitPane.setLeftComponent(menuJPanel);

        cardLayoutJPanel.setLayout(new java.awt.CardLayout());
        splitPane.setRightComponent(cardLayoutJPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 898, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void airlinersBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_airlinersBtnActionPerformed
        // TODO add your handling code here:
        AirlinerCatalogue panel = new AirlinerCatalogue(cardLayoutJPanel, dirAirliner);
        cardLayoutJPanel.add("AirlinerCatalogue", panel);
        CardLayout layout = (CardLayout) cardLayoutJPanel.getLayout();
        layout.next(cardLayoutJPanel);
    }//GEN-LAST:event_airlinersBtnActionPerformed

    private void setFlightScheduleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setFlightScheduleBtnActionPerformed
        // TODO add your handling code here:
        if (airlinerComboBox.getSelectedItem().equals("Select Airliner")) {
            JOptionPane.showMessageDialog(null, "Please select an option above");
            return;
        }
        String airlinerName = airlinerComboBox.getSelectedItem().toString();
        airlinerFlightScheduleJPanel panel = new airlinerFlightScheduleJPanel(cardLayoutJPanel, dirFlight, airlinerName);
        cardLayoutJPanel.add("airlinerFlightScheduleJPanel", panel);
        CardLayout layout = (CardLayout) cardLayoutJPanel.getLayout();
        layout.next(cardLayoutJPanel);
    }//GEN-LAST:event_setFlightScheduleBtnActionPerformed
    private void travelAgencyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_travelAgencyBtnActionPerformed
        // TODO add your handling code here:
        masterFlightScheduleJPanel panel = new masterFlightScheduleJPanel(cardLayoutJPanel, dirFlight);
        cardLayoutJPanel.add("masterFlightScheduleJPanel", panel);
        CardLayout layout = (CardLayout) cardLayoutJPanel.getLayout();
        layout.next(cardLayoutJPanel);
    }//GEN-LAST:event_travelAgencyBtnActionPerformed

    private void customerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerBtnActionPerformed
        // TODO add your handling code here:

        CustomerDashboardJPanel panel = new CustomerDashboardJPanel(cardLayoutJPanel, CustomerDirectory.customerList);
        cardLayoutJPanel.add("CustomerDashboardJPanel", panel);
        CardLayout layout = (CardLayout) cardLayoutJPanel.getLayout();
        layout.next(cardLayoutJPanel);
    }//GEN-LAST:event_customerBtnActionPerformed

    private void airlinerComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_airlinerComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_airlinerComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AirlineAgencyMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AirlineAgencyMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AirlineAgencyMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AirlineAgencyMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AirlineAgencyMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> airlinerComboBox;
    private javax.swing.JButton airlinersBtn;
    private javax.swing.JPanel cardLayoutJPanel;
    private javax.swing.JButton customerBtn;
    private javax.swing.JPanel menuJPanel;
    private javax.swing.JButton setFlightScheduleBtn;
    private javax.swing.JSplitPane splitPane;
    private javax.swing.JButton travelAgencyBtn;
    // End of variables declaration//GEN-END:variables
}
