/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ManageAirliners;

import Business.Airliner;
import Business.AirlinerDirectory;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Charmi Dalal
 */
public class AirlinerCatalogue extends javax.swing.JPanel {

    /* Constructor to populate airliner catalog */
    private final JPanel cardLayoutJPanel;
    private AirlinerDirectory airlineDir;
    
    public AirlinerCatalogue(JPanel cardLayoutJPanel, AirlinerDirectory airlineDir) {
        initComponents();
        this.airlineDir = airlineDir;
        this.cardLayoutJPanel = cardLayoutJPanel;
        populateTable();
    }
    /*Fetch all the airliners and show it in table */
    public void populateTable(){
        DefaultTableModel dtm = (DefaultTableModel)airlineTable.getModel();
        dtm.setRowCount(0);
        
        for(Airliner a : airlineDir.getAirlinerDir()){
            Object[] row = new Object[dtm.getColumnCount()];
            row[0]= a;
            row[1]= a.getAirlineCode();
            row[2] = a.getFromCountry();
            row[3] = a.getAirlineCount();
            dtm.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        airlinerCatalogLbl = new javax.swing.JLabel();
        scrollPanel = new javax.swing.JScrollPane();
        airlineTable = new javax.swing.JTable();
        viewAirlinerBtn = new javax.swing.JButton();
        createAirlinerBtn = new javax.swing.JButton();
        deleteAirlinerBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 204, 255));

        airlinerCatalogLbl.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        airlinerCatalogLbl.setText("Airliners Catalogue");

        airlineTable.setBackground(new java.awt.Color(255, 204, 102));
        airlineTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Airliner Name", "Airline No", "From Country", "Fleet Count"
            }
        ));
        airlineTable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        scrollPanel.setViewportView(airlineTable);

        viewAirlinerBtn.setBackground(new java.awt.Color(255, 204, 102));
        viewAirlinerBtn.setText("View Airliner");
        viewAirlinerBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 0, 0), new java.awt.Color(204, 204, 204), null));
        viewAirlinerBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        viewAirlinerBtn.setPreferredSize(new java.awt.Dimension(135, 40));
        viewAirlinerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewAirlinerBtnActionPerformed(evt);
            }
        });

        createAirlinerBtn.setBackground(new java.awt.Color(255, 204, 102));
        createAirlinerBtn.setText("Create Airliner");
        createAirlinerBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 0, 0), new java.awt.Color(204, 204, 204), null));
        createAirlinerBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        createAirlinerBtn.setPreferredSize(new java.awt.Dimension(135, 40));
        createAirlinerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createAirlinerBtnActionPerformed(evt);
            }
        });

        deleteAirlinerBtn.setBackground(new java.awt.Color(255, 204, 102));
        deleteAirlinerBtn.setText("Delete Airliner");
        deleteAirlinerBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 0, 0), new java.awt.Color(204, 204, 204), null));
        deleteAirlinerBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deleteAirlinerBtn.setPreferredSize(new java.awt.Dimension(135, 40));
        deleteAirlinerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteAirlinerBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(289, 289, 289)
                        .addComponent(airlinerCatalogLbl))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(scrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 731, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(createAirlinerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(153, 153, 153)
                                .addComponent(viewAirlinerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(173, 173, 173)
                                .addComponent(deleteAirlinerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(118, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(airlinerCatalogLbl)
                .addGap(46, 46, 46)
                .addComponent(scrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createAirlinerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewAirlinerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteAirlinerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(234, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    /* Onclick on create go to Create airliner */
    private void createAirlinerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createAirlinerBtnActionPerformed
        // TODO add your handling code here:
        CreateAirlinerJPanel panel = new CreateAirlinerJPanel(cardLayoutJPanel, airlineDir);
        cardLayoutJPanel.add("CreateAirlinerJPanel",panel);
        CardLayout layout = (CardLayout) cardLayoutJPanel.getLayout();
        layout.next(cardLayoutJPanel);
    }//GEN-LAST:event_createAirlinerBtnActionPerformed
    /* Onclick on View go to manage airliner */
    private void viewAirlinerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewAirlinerBtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = airlineTable.getSelectedRow();
        if(selectedRow > -1){
            Airliner airliner = airlineDir.getAirlinerDir().get(selectedRow);
            ViewAirlinerJPanel panel = new ViewAirlinerJPanel(cardLayoutJPanel, airliner);
            cardLayoutJPanel.add("ViewAirlinerJPanel",panel);
            CardLayout layout = (CardLayout) cardLayoutJPanel.getLayout();
            layout.next(cardLayoutJPanel);
        }
        else{
            JOptionPane.showMessageDialog(null, "Kindly select a row first!!");
        }
    }//GEN-LAST:event_viewAirlinerBtnActionPerformed
    /* Delete selected airliner from the directory */
    private void deleteAirlinerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteAirlinerBtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = airlineTable.getSelectedRow();
        if(selectedRow>=0){
            int selectionButton = JOptionPane.YES_NO_OPTION;
            int selectionResult = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete this airliner?","Warning",selectionButton);
            if(selectionResult == JOptionPane.YES_OPTION){
                Airliner airliner = (Airliner)airlineTable.getValueAt(selectedRow, 0);
                airlineDir.removeAirliner(airliner);
                populateTable();
            }
        }else{
            JOptionPane.showMessageDialog(null, "Kindly select a row first!!");
        }
    }//GEN-LAST:event_deleteAirlinerBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable airlineTable;
    private javax.swing.JLabel airlinerCatalogLbl;
    private javax.swing.JButton createAirlinerBtn;
    private javax.swing.JButton deleteAirlinerBtn;
    private javax.swing.JScrollPane scrollPanel;
    private javax.swing.JButton viewAirlinerBtn;
    // End of variables declaration//GEN-END:variables
}
