/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ManageAirliners;

import javax.swing.JPanel;
import Business.Airliner;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;

/**
 *
 * @author Dinesh Kumar
 */
public class ViewAirlinerJPanel extends javax.swing.JPanel {

    /* View Airliner Constructor */
    private final JPanel cardLayoutJPanel;
    private final Airliner airliner;

    public ViewAirlinerJPanel(JPanel cardLayoutJPanel, Airliner airliner) {
        initComponents();
        this.airliner = airliner;
        this.cardLayoutJPanel = cardLayoutJPanel;
        saveBtn.setEnabled(false);
        populateInputs();
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
    /* Set selected airliner */
    private void populateInputs() {
        nameTxt.setText(airliner.getAirlineName());
        fromCountryTxt.setText(airliner.getFromCountry());
        codeTxt.setText(airliner.getAirlineCode());
        noOfFlightsTxt.setText(Integer.toString(airliner.getAirlineCount()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backBtn = new javax.swing.JButton();
        airlinerNameLbl = new javax.swing.JLabel();
        nameTxt = new javax.swing.JTextField();
        airlinerNoLbl = new javax.swing.JLabel();
        codeTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        fromCountryLbl = new javax.swing.JLabel();
        fromCountryTxt = new javax.swing.JTextField();
        fleetCountLbl = new javax.swing.JLabel();
        noOfFlightsTxt = new javax.swing.JTextField();
        updateBtn = new javax.swing.JButton();
        saveBtn = new javax.swing.JButton();
        manageAirlinerTxt = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 204, 255));

        backBtn.setBackground(new java.awt.Color(255, 204, 102));
        backBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        backBtn.setText("Back");
        backBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 0, 0), new java.awt.Color(204, 204, 204), null));
        backBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        airlinerNameLbl.setText("Airliner Name:");

        nameTxt.setBackground(new java.awt.Color(255, 204, 102));
        nameTxt.setEnabled(false);

        airlinerNoLbl.setText("Airliner No:");

        codeTxt.setBackground(new java.awt.Color(255, 204, 102));
        codeTxt.setEnabled(false);

        fromCountryLbl.setText("From Country:");

        fromCountryTxt.setBackground(new java.awt.Color(255, 204, 102));
        fromCountryTxt.setEnabled(false);

        fleetCountLbl.setText("Fleet Count:");

        noOfFlightsTxt.setBackground(new java.awt.Color(255, 204, 102));
        noOfFlightsTxt.setEnabled(false);

        updateBtn.setBackground(new java.awt.Color(255, 204, 102));
        updateBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        updateBtn.setText("Update");
        updateBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 0, 0), new java.awt.Color(204, 204, 204), null));
        updateBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        saveBtn.setBackground(new java.awt.Color(255, 204, 102));
        saveBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        saveBtn.setText("Save");
        saveBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 0, 0), new java.awt.Color(204, 204, 204), null));
        saveBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        manageAirlinerTxt.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        manageAirlinerTxt.setText("Manage Airliner");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(airlinerNoLbl)
                        .addGap(161, 161, 161)
                        .addComponent(codeTxt))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(airlinerNameLbl)
                        .addGap(143, 143, 143)
                        .addComponent(nameTxt))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fromCountryLbl)
                            .addComponent(fleetCountLbl))
                        .addGap(143, 143, 143)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addComponent(updateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                                .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(noOfFlightsTxt)
                            .addComponent(fromCountryTxt))))
                .addGap(224, 224, 224))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(311, 311, 311)
                        .addComponent(manageAirlinerTxt))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(manageAirlinerTxt)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(airlinerNameLbl)
                    .addComponent(nameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(airlinerNoLbl)
                    .addComponent(codeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(fromCountryLbl)
                            .addComponent(fromCountryTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(59, 59, 59)
                        .addComponent(fleetCountLbl))
                    .addComponent(noOfFlightsTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82))
        );
    }// </editor-fold>//GEN-END:initComponents
    /* Click on back go to main airliner manager */
    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        cardLayoutJPanel.remove(this);
        CardLayout layout = (CardLayout) cardLayoutJPanel.getLayout();

        Component[] components = cardLayoutJPanel.getComponents();
        for (Component component : components) {
            if (component instanceof AirlinerCatalogue) {
                AirlinerCatalogue mpp = (AirlinerCatalogue) component;
                mpp.populateTable();
            }
        }
        layout.previous(cardLayoutJPanel);
    }//GEN-LAST:event_backBtnActionPerformed
    /* Onclick on update button set new values */
    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // TODO add your handling code here:
        nameTxt.setEnabled(true);
        fromCountryTxt.setEnabled(true);
        codeTxt.setEnabled(true);
        noOfFlightsTxt.setEnabled(true);
        updateBtn.setEnabled(false);
        saveBtn.setEnabled(true);
    }//GEN-LAST:event_updateBtnActionPerformed
    /* On save check if all text boxes are filled */
    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        // TODO add your handling code here:
        if (nameTxt.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please Enter Airline Name.");
            return;
        }

        if (codeTxt.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please Enter Airline No.");
            return;
        }

        if (fromCountryTxt.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please Enter Country");
            return;
        }

        try {
            Integer.parseInt(noOfFlightsTxt.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Please Enter Number of Fleet");
            return;
        }

        airliner.setAirlineCode(codeTxt.getText());
        airliner.setAirlineName(nameTxt.getText());
        airliner.setAirlineCount((int) Double.parseDouble(noOfFlightsTxt.getText()));
        airliner.setFromCountry(fromCountryTxt.getText());
        JOptionPane.showMessageDialog(null, "Airliner Updated Successfully");
        nameTxt.setEnabled(false);
        noOfFlightsTxt.setEnabled(false);
        fromCountryTxt.setEnabled(false);
        codeTxt.setEnabled(false);
        updateBtn.setEnabled(true);
        saveBtn.setEnabled(false);
    }//GEN-LAST:event_saveBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel airlinerNameLbl;
    private javax.swing.JLabel airlinerNoLbl;
    private javax.swing.JButton backBtn;
    private javax.swing.JTextField codeTxt;
    private javax.swing.JLabel fleetCountLbl;
    private javax.swing.JLabel fromCountryLbl;
    private javax.swing.JTextField fromCountryTxt;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel manageAirlinerTxt;
    private javax.swing.JTextField nameTxt;
    private javax.swing.JTextField noOfFlightsTxt;
    private javax.swing.JButton saveBtn;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
