/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.Person;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author charmidalal
 */
public class ViewPersonJpanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewPersonJpanel
     */
    
    public ViewPersonJpanel(Person person) {
        initComponents();
        /* On click of diplay show the added person profile */
        displayPerson(person);
    }
    
    /* This method shows value from the objects in textboxes */
    private void displayPerson(Person person)
    {       
        /* fetch values from person object and display it in textboxes */
        firstNameTxtbox.setText(person.getFirstName());
        lastNameTxtbox.setText(person.getLastName());
        dobTxtbox.setText(person.getBirthDate());
        telNumTxtbox.setText(person.getTelNum());
        faxNumTxtbox.setText(person.getFaxNum());
        emailAddTxtbox.setText(person.getEmailAddress());
        streetAddTxtbox.setText(person.getStreetAddrs1());
        streetAdd2Txtbox.setText(person.getStreetAddrs2());
        cityTxtbox.setText(person.getCity());
        stateTxtbox.setText(person.getState());
        zipcodeTxtbox.setText(person.getZipcode());
        ssnNoTxtbox.setText(person.getSsnNum());
        medicalRecNoTxtbox.setText(person.getMedicalRecNo());
        healthPlanNoTxtbox.setText(person.getHealthPlanNo());
        bankAccNoTxtbox.setText(person.getBankAccNo());
        licenseNoTxtbox.setText(person.getLicenseNo());
        vehicleNoTxtbox.setText(person.getVehicleNo());
        deviceNoTxtbox.setText(person.getDeviceNo());
        linkedInTxtbox.setText(person.getLinkedIn());
        biometricNoTxtbox.setText(person.getBiometric());
        uniqueIdentityNoTxtbox.setText(person.getUniqueIdentityNo());
        iPAddrTxtbox.setText(person.getIpAddr());
        /* Check if image is saved or not, Display image ferom saved image path */
        if(person.isSaveFlag()){
            ImageIcon imageIcon = new ImageIcon(new ImageIcon(person.getImagePath()).getImage().getScaledInstance(200, 200, Image.SCALE_DEFAULT));
            fullImgDisplayLbl.setIcon(imageIcon);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        stateTxtbox = new javax.swing.JTextField();
        zipcodeLbl = new javax.swing.JLabel();
        zipcodeTxtbox = new javax.swing.JTextField();
        otherDetailsLbl = new javax.swing.JLabel();
        ssnNoLbl = new javax.swing.JLabel();
        ssnNoTxtbox = new javax.swing.JTextField();
        medicalRecLbl = new javax.swing.JLabel();
        medicalRecNoTxtbox = new javax.swing.JTextField();
        healthPlanNoLbl = new javax.swing.JLabel();
        healthPlanNoTxtbox = new javax.swing.JTextField();
        vehicleNoTxtbox = new javax.swing.JTextField();
        bankAccNoLbl = new javax.swing.JLabel();
        LicenseNoLbl = new javax.swing.JLabel();
        bankAccNoTxtbox = new javax.swing.JTextField();
        vehicleNoLbl = new javax.swing.JLabel();
        licenseNoTxtbox = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        deviceNoTxtbox = new javax.swing.JTextField();
        linkedInLbl = new javax.swing.JLabel();
        iPAddrTxtbox = new javax.swing.JTextField();
        personDetailsLbl = new javax.swing.JLabel();
        IPAddrLbl = new javax.swing.JLabel();
        linkedInTxtbox = new javax.swing.JTextField();
        biometricLbl = new javax.swing.JLabel();
        biometricNoTxtbox = new javax.swing.JTextField();
        firstNameLbl = new javax.swing.JLabel();
        fullImgLbl = new javax.swing.JLabel();
        lastNameLbl = new javax.swing.JLabel();
        lastNameTxtbox = new javax.swing.JTextField();
        uniqueIdentityNoLbl = new javax.swing.JLabel();
        firstNameTxtbox = new javax.swing.JTextField();
        uniqueIdentityNoTxtbox = new javax.swing.JTextField();
        dobLbl = new javax.swing.JLabel();
        dobTxtbox = new javax.swing.JTextField();
        telNumLbl = new javax.swing.JLabel();
        telNumTxtbox = new javax.swing.JTextField();
        faxNumLbl = new javax.swing.JLabel();
        faxNumTxtbox = new javax.swing.JTextField();
        emailAddLbl = new javax.swing.JLabel();
        emailAddTxtbox = new javax.swing.JTextField();
        personAddLbl = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        streetAddTxtbox = new javax.swing.JTextField();
        streetAdd2Lbl = new javax.swing.JLabel();
        streetAdd2Txtbox = new javax.swing.JTextField();
        cityLbl = new javax.swing.JLabel();
        cityTxtbox = new javax.swing.JTextField();
        stateLbl = new javax.swing.JLabel();
        fullImgDisplayLbl = new javax.swing.JLabel();

        stateTxtbox.setEditable(false);

        zipcodeLbl.setText("Zipcode:");

        zipcodeTxtbox.setEditable(false);

        otherDetailsLbl.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        otherDetailsLbl.setText("Other Details");

        ssnNoLbl.setText("SSN No:");

        ssnNoTxtbox.setEditable(false);
        ssnNoTxtbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ssnNoTxtboxActionPerformed(evt);
            }
        });

        medicalRecLbl.setText("Medical Rec No:");

        medicalRecNoTxtbox.setEditable(false);

        healthPlanNoLbl.setText("Health Plan No:");

        healthPlanNoTxtbox.setEditable(false);

        vehicleNoTxtbox.setEditable(false);

        bankAccNoLbl.setText("Bank Acc No:");

        LicenseNoLbl.setText("License No:");

        bankAccNoTxtbox.setEditable(false);

        vehicleNoLbl.setText("Vehicle No:");

        licenseNoTxtbox.setEditable(false);

        jLabel5.setText("Device No:");

        deviceNoTxtbox.setEditable(false);

        linkedInLbl.setText("LinkedIn");

        iPAddrTxtbox.setEditable(false);

        personDetailsLbl.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        personDetailsLbl.setText("Person Details");

        IPAddrLbl.setText("IP Address:");

        linkedInTxtbox.setEditable(false);

        biometricLbl.setText("Biometric:");

        biometricNoTxtbox.setEditable(false);

        firstNameLbl.setText("First Name:");

        fullImgLbl.setText("Full Image:");

        lastNameLbl.setText("Last Name:");

        lastNameTxtbox.setEditable(false);

        uniqueIdentityNoLbl.setText("Unique Identity No:");

        firstNameTxtbox.setEditable(false);

        uniqueIdentityNoTxtbox.setEditable(false);

        dobLbl.setText("DOB:");

        dobTxtbox.setEditable(false);

        telNumLbl.setText("Tel No:");

        telNumTxtbox.setEditable(false);
        telNumTxtbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telNumTxtboxActionPerformed(evt);
            }
        });

        faxNumLbl.setText("Fax No:");

        faxNumTxtbox.setEditable(false);
        faxNumTxtbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                faxNumTxtboxActionPerformed(evt);
            }
        });

        emailAddLbl.setText("Email Address:");

        emailAddTxtbox.setEditable(false);

        personAddLbl.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        personAddLbl.setText("Person Address");

        jLabel2.setText("Street Addrs 1:");

        streetAddTxtbox.setEditable(false);
        streetAddTxtbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                streetAddTxtboxActionPerformed(evt);
            }
        });

        streetAdd2Lbl.setText("Street Addrs 2:");

        streetAdd2Txtbox.setEditable(false);

        cityLbl.setText("City:");

        cityTxtbox.setEditable(false);
        cityTxtbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cityTxtboxActionPerformed(evt);
            }
        });

        stateLbl.setText("State:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(firstNameLbl)
                                    .addComponent(telNumLbl))
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(firstNameTxtbox, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                    .addComponent(telNumTxtbox)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(stateLbl)
                                    .addComponent(ssnNoLbl)
                                    .addComponent(bankAccNoLbl)
                                    .addComponent(jLabel5)
                                    .addComponent(biometricLbl))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(streetAddTxtbox)
                                    .addComponent(stateTxtbox)
                                    .addComponent(ssnNoTxtbox)
                                    .addComponent(bankAccNoTxtbox, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                                    .addComponent(deviceNoTxtbox)
                                    .addComponent(biometricNoTxtbox, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGap(106, 106, 106)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(faxNumLbl)
                                    .addComponent(streetAdd2Lbl)
                                    .addComponent(lastNameLbl)
                                    .addComponent(zipcodeLbl))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(50, 50, 50)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(faxNumTxtbox, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lastNameTxtbox, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(53, 53, 53)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(fullImgDisplayLbl)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(licenseNoTxtbox)
                                                .addComponent(medicalRecNoTxtbox)
                                                .addComponent(zipcodeTxtbox)
                                                .addComponent(streetAdd2Txtbox)
                                                .addComponent(linkedInTxtbox, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE))))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LicenseNoLbl)
                                    .addComponent(medicalRecLbl)
                                    .addComponent(linkedInLbl)
                                    .addComponent(fullImgLbl))))
                        .addGap(101, 101, 101)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cityLbl)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dobLbl)
                                    .addComponent(emailAddLbl)
                                    .addComponent(healthPlanNoLbl)
                                    .addComponent(vehicleNoLbl)
                                    .addComponent(IPAddrLbl)
                                    .addComponent(uniqueIdentityNoLbl))
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(uniqueIdentityNoTxtbox, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(iPAddrTxtbox, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(dobTxtbox, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                        .addComponent(emailAddTxtbox, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cityTxtbox, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(healthPlanNoTxtbox)
                                        .addComponent(vehicleNoTxtbox))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(469, 469, 469)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(personAddLbl)
                            .addComponent(personDetailsLbl)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(474, 474, 474)
                        .addComponent(otherDetailsLbl)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(personDetailsLbl)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstNameLbl)
                    .addComponent(lastNameLbl)
                    .addComponent(lastNameTxtbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(firstNameTxtbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dobLbl)
                    .addComponent(dobTxtbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telNumLbl)
                    .addComponent(telNumTxtbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(faxNumLbl)
                    .addComponent(faxNumTxtbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailAddLbl)
                    .addComponent(emailAddTxtbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(personAddLbl)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(streetAddTxtbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(streetAdd2Lbl)
                    .addComponent(streetAdd2Txtbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cityLbl)
                    .addComponent(cityTxtbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stateLbl)
                    .addComponent(stateTxtbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(zipcodeLbl)
                    .addComponent(zipcodeTxtbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addComponent(otherDetailsLbl)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ssnNoLbl)
                    .addComponent(ssnNoTxtbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(medicalRecLbl)
                    .addComponent(medicalRecNoTxtbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(healthPlanNoLbl)
                    .addComponent(healthPlanNoTxtbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vehicleNoTxtbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bankAccNoLbl)
                    .addComponent(LicenseNoLbl)
                    .addComponent(bankAccNoTxtbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vehicleNoLbl)
                    .addComponent(licenseNoTxtbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(deviceNoTxtbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(linkedInLbl)
                    .addComponent(iPAddrTxtbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IPAddrLbl)
                    .addComponent(linkedInTxtbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(biometricLbl)
                    .addComponent(biometricNoTxtbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fullImgLbl)
                    .addComponent(uniqueIdentityNoLbl)
                    .addComponent(uniqueIdentityNoTxtbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fullImgDisplayLbl))
                .addContainerGap(76, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ssnNoTxtboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ssnNoTxtboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ssnNoTxtboxActionPerformed

    private void telNumTxtboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telNumTxtboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telNumTxtboxActionPerformed

    private void faxNumTxtboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_faxNumTxtboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_faxNumTxtboxActionPerformed

    private void streetAddTxtboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_streetAddTxtboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_streetAddTxtboxActionPerformed

    private void cityTxtboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cityTxtboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cityTxtboxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IPAddrLbl;
    private javax.swing.JLabel LicenseNoLbl;
    private javax.swing.JLabel bankAccNoLbl;
    private javax.swing.JTextField bankAccNoTxtbox;
    private javax.swing.JLabel biometricLbl;
    private javax.swing.JTextField biometricNoTxtbox;
    private javax.swing.JLabel cityLbl;
    private javax.swing.JTextField cityTxtbox;
    private javax.swing.JTextField deviceNoTxtbox;
    private javax.swing.JLabel dobLbl;
    private javax.swing.JTextField dobTxtbox;
    private javax.swing.JLabel emailAddLbl;
    private javax.swing.JTextField emailAddTxtbox;
    private javax.swing.JLabel faxNumLbl;
    private javax.swing.JTextField faxNumTxtbox;
    private javax.swing.JLabel firstNameLbl;
    private javax.swing.JTextField firstNameTxtbox;
    private javax.swing.JLabel fullImgDisplayLbl;
    private javax.swing.JLabel fullImgLbl;
    private javax.swing.JLabel healthPlanNoLbl;
    private javax.swing.JTextField healthPlanNoTxtbox;
    private javax.swing.JTextField iPAddrTxtbox;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lastNameLbl;
    private javax.swing.JTextField lastNameTxtbox;
    private javax.swing.JTextField licenseNoTxtbox;
    private javax.swing.JLabel linkedInLbl;
    private javax.swing.JTextField linkedInTxtbox;
    private javax.swing.JLabel medicalRecLbl;
    private javax.swing.JTextField medicalRecNoTxtbox;
    private javax.swing.JLabel otherDetailsLbl;
    private javax.swing.JLabel personAddLbl;
    private javax.swing.JLabel personDetailsLbl;
    private javax.swing.JLabel ssnNoLbl;
    private javax.swing.JTextField ssnNoTxtbox;
    private javax.swing.JLabel stateLbl;
    private javax.swing.JTextField stateTxtbox;
    private javax.swing.JLabel streetAdd2Lbl;
    private javax.swing.JTextField streetAdd2Txtbox;
    private javax.swing.JTextField streetAddTxtbox;
    private javax.swing.JLabel telNumLbl;
    private javax.swing.JTextField telNumTxtbox;
    private javax.swing.JLabel uniqueIdentityNoLbl;
    private javax.swing.JTextField uniqueIdentityNoTxtbox;
    private javax.swing.JLabel vehicleNoLbl;
    private javax.swing.JTextField vehicleNoTxtbox;
    private javax.swing.JLabel zipcodeLbl;
    private javax.swing.JTextField zipcodeTxtbox;
    // End of variables declaration//GEN-END:variables
}
